/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CoD.gui;

import CoD.DBConnect;
import CoD.EmailValidator;
import CoD.PasswordValidator;
import CoD.User;
import CoD.Basket;
import CoD.menu.*;
import java.awt.CardLayout;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Stefan
 */
public class ClientWindow extends javax.swing.JFrame 
{
    private static DBConnect            conn;
    private static User                 user;
    private final EmailValidator        ev;
    private final PasswordValidator     pv, pvRepeat;
    private static AbstractMenu         bfMenu = new BreakfastMenu();
    private static final Basket         basket = new Basket();
    /**
     * Creates new form MainWindow
     * @param conn
     * @param user
     */
    public ClientWindow(DBConnect conn, User user) {
        initComponents();
        this.conn = conn;
        this.user = user;
        
        ev = new EmailValidator(
                accountNewEmailField.getParent(),
                accountNewEmailField);
        pv = new PasswordValidator(
                accountNewPassField.getParent(),
                accountNewPassField,
                accountNewPassField);
        pvRepeat = new PasswordValidator(
                accountNewPass2Field.getParent(),
                accountNewPassField,
                accountNewPass2Field);
        
        accountNewEmailField.setInputVerifier(ev);
        accountNewPassField.setInputVerifier(pv);
        accountNewPass2Field.setInputVerifier(pvRepeat);
        
        homeWelcomeLbl.setText("Welcome, " + user.getName() + ".");
        
        bfMenu.addProduct(new Product("title", "desc", 12, "breakfast", 5));
        bfMenu.addProduct(new Product("title", "desc", 10, "breakfast", 5));
        bfMenu = AbstractMenu.buildMenu(conn, "breakfast");
        System.out.println(bfMenu.getProduct(0).getName());
        
        java.awt.event.WindowListener exitListener = new WindowAdapter(user);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(exitListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuSelector = new javax.swing.ButtonGroup();
        payTypeSelector = new javax.swing.ButtonGroup();
        accountManagerSelect = new javax.swing.ButtonGroup();
        orderDialog = new javax.swing.JDialog();
        orderBtnPanel = new javax.swing.JPanel();
        cardPaySelect = new javax.swing.JRadioButton();
        bankPaySelect = new javax.swing.JRadioButton();
        priorityBox = new javax.swing.JCheckBox();
        paymentTotalCostLbl = new javax.swing.JLabel();
        paymentTotalCostField = new javax.swing.JTextField();
        orderPayPanel = new javax.swing.JPanel();
        cardPayPanel = new javax.swing.JPanel();
        cardTypeLbl = new javax.swing.JLabel();
        cardTypeBox = new javax.swing.JComboBox();
        cardNameLbl = new javax.swing.JLabel();
        cardNameField = new javax.swing.JTextField();
        cardNoLbl = new javax.swing.JLabel();
        cardNoField = new javax.swing.JTextField();
        CardExpDateLbl = new javax.swing.JLabel();
        cardMonthBox = new javax.swing.JComboBox();
        cardYearBox = new javax.swing.JComboBox();
        cardCodeLbl = new javax.swing.JLabel();
        cardCodeField = new javax.swing.JTextField();
        orderBtnCard = new javax.swing.JButton();
        bankPayPanel = new javax.swing.JPanel();
        bankAccNameLbl = new javax.swing.JLabel();
        bankAccNameField = new javax.swing.JTextField();
        bankAccNoLbl = new javax.swing.JLabel();
        bankAccNoField = new javax.swing.JTextField();
        bankSortCodeLbl = new javax.swing.JLabel();
        bankSortCodeF1 = new javax.swing.JTextField();
        bankSortCodeF2 = new javax.swing.JTextField();
        bankSortCodeF3 = new javax.swing.JTextField();
        orderBtnBank = new javax.swing.JButton();
        clientTabs = new javax.swing.JTabbedPane();
        homeTab = new javax.swing.JPanel();
        homeWelcomeLbl = new javax.swing.JLabel();
        homeVIPStatusLbl = new javax.swing.JLabel();
        homeVIPStatusField = new javax.swing.JTextField();
        homeNextStatusLbl = new javax.swing.JLabel();
        homeNextStatusField = new javax.swing.JTextField();
        homeDiscountPlanLbl = new javax.swing.JLabel();
        homeDiscountPlanField = new javax.swing.JTextField();
        homeLogoutBtn = new javax.swing.JButton();
        menuTab = new javax.swing.JPanel();
        breakfastSelect = new javax.swing.JRadioButton();
        lunchSelect = new javax.swing.JRadioButton();
        dinnerSelect = new javax.swing.JRadioButton();
        drinksSelect = new javax.swing.JRadioButton();
        orderTotalCostLbl = new javax.swing.JLabel();
        orderTotalCostField = new javax.swing.JTextField();
        orderBtn = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        breakfastMenuSP = new javax.swing.JScrollPane();
        breakfastMenuPanel = new javax.swing.JPanel();
        PN1 = new javax.swing.JCheckBox();
        PD1 = new javax.swing.JLabel();
        PP1 = new javax.swing.JLabel();
        PN2 = new javax.swing.JCheckBox();
        PD2 = new javax.swing.JLabel();
        PP2 = new javax.swing.JLabel();
        PN3 = new javax.swing.JCheckBox();
        PD3 = new javax.swing.JLabel();
        PP3 = new javax.swing.JLabel();
        PN4 = new javax.swing.JCheckBox();
        PD4 = new javax.swing.JLabel();
        PP4 = new javax.swing.JLabel();
        PN5 = new javax.swing.JCheckBox();
        PD5 = new javax.swing.JLabel();
        PP5 = new javax.swing.JLabel();
        PN6 = new javax.swing.JCheckBox();
        PD6 = new javax.swing.JLabel();
        PP6 = new javax.swing.JLabel();
        PN7 = new javax.swing.JCheckBox();
        PD7 = new javax.swing.JLabel();
        PP7 = new javax.swing.JLabel();
        PN8 = new javax.swing.JCheckBox();
        PD8 = new javax.swing.JLabel();
        PP8 = new javax.swing.JLabel();
        basketSP = new javax.swing.JScrollPane();
        basketTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        orderHistoryTab = new javax.swing.JPanel();
        orderHistoryScrollPanel = new javax.swing.JScrollPane();
        orderHistoryTable = new javax.swing.JTable();
        totalSpentLbl = new javax.swing.JLabel();
        totalSpentField = new javax.swing.JTextField();
        accountTab = new javax.swing.JPanel();
        accountChangeEmailSelect = new javax.swing.JRadioButton();
        accountChangePassSelect = new javax.swing.JRadioButton();
        accountPassLbl = new javax.swing.JLabel();
        accountPassField = new javax.swing.JPasswordField();
        accountNewEmailLbl = new javax.swing.JLabel();
        accountNewEmailField = new javax.swing.JTextField();
        accountChangeEmailBtn = new javax.swing.JButton();
        accountOldPassLbl = new javax.swing.JLabel();
        accountOldPassField = new javax.swing.JPasswordField();
        accountNewPassLbl = new javax.swing.JLabel();
        accountNewPassField = new javax.swing.JPasswordField();
        accountNewPass2Lbl = new javax.swing.JLabel();
        accountNewPass2Field = new javax.swing.JPasswordField();
        accountChangePassBtn = new javax.swing.JButton();

        orderDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        orderDialog.setLocationByPlatform(true);
        orderDialog.setMinimumSize(new java.awt.Dimension(280, 340));
        orderDialog.getContentPane().setLayout(new javax.swing.BoxLayout(orderDialog.getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        orderBtnPanel.setMinimumSize(new java.awt.Dimension(270, 80));
        orderBtnPanel.setPreferredSize(new java.awt.Dimension(270, 80));

        payTypeSelector.add(cardPaySelect);
        cardPaySelect.setSelected(true);
        cardPaySelect.setText("Credit/Debit card");
        cardPaySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardPaySelectActionPerformed(evt);
            }
        });

        payTypeSelector.add(bankPaySelect);
        bankPaySelect.setText("Bank transfer");
        bankPaySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankPaySelectActionPerformed(evt);
            }
        });

        priorityBox.setText("<html>Priority Order<br>(+5% in cost)");
        priorityBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorityBoxActionPerformed(evt);
            }
        });

        paymentTotalCostLbl.setText("Total cost");

        paymentTotalCostField.setEditable(false);
        paymentTotalCostField.setText("15");
        paymentTotalCostField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentTotalCostFieldActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout orderBtnPanelLayout = new org.jdesktop.layout.GroupLayout(orderBtnPanel);
        orderBtnPanel.setLayout(orderBtnPanelLayout);
        orderBtnPanelLayout.setHorizontalGroup(
            orderBtnPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(orderBtnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(orderBtnPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(orderBtnPanelLayout.createSequentialGroup()
                        .add(paymentTotalCostLbl)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(paymentTotalCostField))
                    .add(cardPaySelect)
                    .add(bankPaySelect))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 60, Short.MAX_VALUE)
                .add(priorityBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        orderBtnPanelLayout.setVerticalGroup(
            orderBtnPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(orderBtnPanelLayout.createSequentialGroup()
                .add(orderBtnPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(orderBtnPanelLayout.createSequentialGroup()
                        .add(cardPaySelect)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bankPaySelect))
                    .add(orderBtnPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(priorityBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(orderBtnPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(paymentTotalCostLbl)
                    .add(paymentTotalCostField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        orderDialog.getContentPane().add(orderBtnPanel);

        orderPayPanel.setPreferredSize(new java.awt.Dimension(260, 260));
        orderPayPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                orderPayPanelComponentShown(evt);
            }
        });
        orderPayPanel.setLayout(new java.awt.CardLayout());

        cardPayPanel.setMinimumSize(new java.awt.Dimension(270, 260));
        cardPayPanel.setPreferredSize(new java.awt.Dimension(270, 260));

        cardTypeLbl.setLabelFor(cardTypeBox);
        cardTypeLbl.setText("Card Type");

        cardTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Visa", "Visa Electron", "Master Card" }));

        cardNameLbl.setText("Cardholder Name");

        cardNameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cardNameField.setMinimumSize(new java.awt.Dimension(149, 30));
        cardNameField.setPreferredSize(new java.awt.Dimension(149, 26));

        cardNoLbl.setLabelFor(cardNoField);
        cardNoLbl.setText("Card Number");

        cardNoField.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        cardNoField.setMaximumSize(new java.awt.Dimension(149, 26));
        cardNoField.setMinimumSize(new java.awt.Dimension(147, 26));
        cardNoField.setPreferredSize(new java.awt.Dimension(147, 26));
        cardNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNoFieldActionPerformed(evt);
            }
        });

        CardExpDateLbl.setText("Expiration date");

        cardMonthBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        cardYearBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "'15", "'16", "'17", "'18", "'19" }));
        cardYearBox.setPreferredSize(new java.awt.Dimension(55, 26));

        cardCodeLbl.setText("<html>Security Code<br>(CVC/CVC2)");

        cardCodeField.setColumns(3);
        cardCodeField.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        cardCodeField.setMaximumSize(new java.awt.Dimension(35, 20));
        cardCodeField.setMinimumSize(new java.awt.Dimension(36, 20));
        cardCodeField.setPreferredSize(new java.awt.Dimension(36, 25));

        orderBtnCard.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        orderBtnCard.setText("Complete Order");
        orderBtnCard.setMargin(new java.awt.Insets(2, 4, 2, 4));
        orderBtnCard.setMaximumSize(new java.awt.Dimension(130, 25));
        orderBtnCard.setMinimumSize(new java.awt.Dimension(130, 25));
        orderBtnCard.setPreferredSize(new java.awt.Dimension(130, 25));
        orderBtnCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnCardActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout cardPayPanelLayout = new org.jdesktop.layout.GroupLayout(cardPayPanel);
        cardPayPanel.setLayout(cardPayPanelLayout);
        cardPayPanelLayout.setHorizontalGroup(
            cardPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(cardPayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(cardPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, cardPayPanelLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(orderBtnCard, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(61, 61, 61))
                    .add(cardPayPanelLayout.createSequentialGroup()
                        .add(cardPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(cardPayPanelLayout.createSequentialGroup()
                                .add(24, 24, 24)
                                .add(cardNoLbl)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(cardNoField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(cardPayPanelLayout.createSequentialGroup()
                                .add(cardPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(cardPayPanelLayout.createSequentialGroup()
                                        .add(cardNameLbl)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(cardNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(cardPayPanelLayout.createSequentialGroup()
                                        .add(cardPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(cardPayPanelLayout.createSequentialGroup()
                                                .add(41, 41, 41)
                                                .add(cardTypeLbl))
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, CardExpDateLbl)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, cardCodeLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(cardPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(cardCodeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(cardTypeBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(cardPayPanelLayout.createSequentialGroup()
                                                .add(cardMonthBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(cardYearBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                                .add(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        cardPayPanelLayout.setVerticalGroup(
            cardPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(cardPayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(cardPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cardTypeLbl)
                    .add(cardTypeBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(cardPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cardNameLbl)
                    .add(cardNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(cardPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cardNoLbl)
                    .add(cardNoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(cardPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cardMonthBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cardYearBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(CardExpDateLbl))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(cardPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cardCodeLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cardCodeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(orderBtnCard, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        orderPayPanel.add(cardPayPanel, "cardPay");

        bankPayPanel.setMinimumSize(new java.awt.Dimension(270, 260));
        bankPayPanel.setPreferredSize(new java.awt.Dimension(270, 260));

        bankAccNameLbl.setText("Account Name");

        bankAccNameField.setMinimumSize(new java.awt.Dimension(149, 28));
        bankAccNameField.setPreferredSize(new java.awt.Dimension(149, 25));

        bankAccNoLbl.setText("Account Number");

        bankAccNoField.setColumns(10);
        bankAccNoField.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        bankAccNoField.setMinimumSize(new java.awt.Dimension(149, 26));
        bankAccNoField.setPreferredSize(new java.awt.Dimension(149, 25));
        bankAccNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankAccNoFieldActionPerformed(evt);
            }
        });

        bankSortCodeLbl.setText("Sort Code");

        bankSortCodeF1.setColumns(2);
        bankSortCodeF1.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        bankSortCodeF1.setPreferredSize(new java.awt.Dimension(28, 25));

        bankSortCodeF2.setColumns(2);
        bankSortCodeF2.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        bankSortCodeF2.setPreferredSize(new java.awt.Dimension(28, 25));

        bankSortCodeF3.setColumns(2);
        bankSortCodeF3.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        bankSortCodeF3.setPreferredSize(new java.awt.Dimension(28, 25));

        orderBtnBank.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        orderBtnBank.setText("Complete Order");
        orderBtnBank.setMargin(new java.awt.Insets(2, 4, 2, 4));
        orderBtnBank.setMaximumSize(new java.awt.Dimension(130, 25));
        orderBtnBank.setMinimumSize(new java.awt.Dimension(130, 25));
        orderBtnBank.setPreferredSize(new java.awt.Dimension(130, 25));
        orderBtnBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnBankActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout bankPayPanelLayout = new org.jdesktop.layout.GroupLayout(bankPayPanel);
        bankPayPanel.setLayout(bankPayPanelLayout);
        bankPayPanelLayout.setHorizontalGroup(
            bankPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bankPayPanelLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(bankPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(bankAccNoLbl)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, bankSortCodeLbl)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, bankAccNameLbl))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(bankPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(bankPayPanelLayout.createSequentialGroup()
                        .add(bankSortCodeF3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bankSortCodeF1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bankSortCodeF2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(bankAccNameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .add(bankAccNoField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(5, 5, 5))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, bankPayPanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(orderBtnBank, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(67, 67, 67))
        );
        bankPayPanelLayout.setVerticalGroup(
            bankPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bankPayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(bankPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bankAccNameLbl)
                    .add(bankAccNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(bankPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bankAccNoLbl)
                    .add(bankAccNoField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(bankPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(bankPayPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(bankSortCodeF3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(bankSortCodeF1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(bankSortCodeF2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(bankSortCodeLbl))
                .add(92, 92, 92)
                .add(orderBtnBank, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25))
        );

        orderPayPanel.add(bankPayPanel, "bankPay");
        bankPayPanel.getAccessibleContext().setAccessibleDescription("");

        orderDialog.getContentPane().add(orderPayPanel);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catering On Demand");
        setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(590, 532));
        setName("MainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(590, 532));

        clientTabs.setFocusCycleRoot(true);
        clientTabs.setFont(clientTabs.getFont().deriveFont(clientTabs.getFont().getSize()+1f));
        clientTabs.setName("TabPanel"); // NOI18N
        clientTabs.setOpaque(true);
        clientTabs.setPreferredSize(new java.awt.Dimension(570, 500));

        homeTab.setName("Home"); // NOI18N

        homeWelcomeLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        homeWelcomeLbl.setText("Welcome, <customer name>.");

        homeVIPStatusLbl.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        homeVIPStatusLbl.setText("VIP Status");

        homeVIPStatusField.setEditable(false);
        homeVIPStatusField.setColumns(7);
        homeVIPStatusField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        homeVIPStatusField.setText("Silver");

        homeNextStatusLbl.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        homeNextStatusLbl.setText("<html>Amount to spend<br>for the next VIP tier");

        homeNextStatusField.setEditable(false);
        homeNextStatusField.setColumns(4);
        homeNextStatusField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        homeNextStatusField.setText("550");

        homeDiscountPlanLbl.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        homeDiscountPlanLbl.setText("Current discount plan");

        homeDiscountPlanField.setEditable(false);
        homeDiscountPlanField.setText("Fixed, 5%");

        homeLogoutBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        homeLogoutBtn.setText("Log out");
        homeLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeLogoutBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout homeTabLayout = new org.jdesktop.layout.GroupLayout(homeTab);
        homeTab.setLayout(homeTabLayout);
        homeTabLayout.setHorizontalGroup(
            homeTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, homeTabLayout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .add(homeTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(homeTabLayout.createSequentialGroup()
                        .add(homeTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(homeNextStatusLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(homeVIPStatusLbl)
                            .add(homeDiscountPlanLbl))
                        .add(18, 18, 18)
                        .add(homeTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(homeVIPStatusField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(homeDiscountPlanField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(homeNextStatusField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(homeTabLayout.createSequentialGroup()
                        .add(homeWelcomeLbl)
                        .add(18, 18, 18)
                        .add(homeLogoutBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        homeTabLayout.setVerticalGroup(
            homeTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(homeTabLayout.createSequentialGroup()
                .add(28, 28, 28)
                .add(homeTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(homeLogoutBtn)
                    .add(homeWelcomeLbl))
                .add(47, 47, 47)
                .add(homeTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(homeVIPStatusLbl)
                    .add(homeVIPStatusField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(22, 22, 22)
                .add(homeTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(homeNextStatusLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(homeNextStatusField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(homeTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(homeDiscountPlanLbl)
                    .add(homeDiscountPlanField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        clientTabs.addTab("Home", homeTab);
        homeTab.getAccessibleContext().setAccessibleName("homeTab");

        menuTab.setPreferredSize(new java.awt.Dimension(570, 500));

        menuSelector.add(breakfastSelect);
        breakfastSelect.setSelected(true);
        breakfastSelect.setText("Breakfast");

        menuSelector.add(lunchSelect);
        lunchSelect.setText("Lunch");

        menuSelector.add(dinnerSelect);
        dinnerSelect.setText("Dinner");

        menuSelector.add(drinksSelect);
        drinksSelect.setText("Drinks");

        orderTotalCostLbl.setText("Total cost");

        orderTotalCostField.setEditable(false);
        orderTotalCostField.setColumns(3);
        orderTotalCostField.setText("0");
        orderTotalCostField.setFocusable(false);
        orderTotalCostField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderTotalCostFieldActionPerformed(evt);
            }
        });

        orderBtn.setText("Place Order");
        orderBtn.setDoubleBuffered(true);
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnActionPerformed(evt);
            }
        });

        menuPanel.setPreferredSize(new java.awt.Dimension(301, 365));
        menuPanel.setLayout(new java.awt.CardLayout());

        breakfastMenuSP.setPreferredSize(new java.awt.Dimension(600, 100));

        breakfastMenuPanel.setPreferredSize(new java.awt.Dimension(274, 604));

        PN1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PN1.setText("Product Name");
        PN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PN1ActionPerformed(evt);
            }
        });

        PD1.setLabelFor(PN1);
        PD1.setText("<Product description>");
        PD1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PD1.setMaximumSize(new java.awt.Dimension(110, 15));
        PD1.setMinimumSize(new java.awt.Dimension(110, 15));
        PD1.setPreferredSize(new java.awt.Dimension(110, 15));

        PP1.setLabelFor(PN1);
        PP1.setText("12");

        PN2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PN2.setText("Product Name");
        PN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PN2ActionPerformed(evt);
            }
        });

        PD2.setLabelFor(PN1);
        PD2.setText("<Product description>");
        PD2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PD2.setMaximumSize(new java.awt.Dimension(110, 15));
        PD2.setMinimumSize(new java.awt.Dimension(110, 15));
        PD2.setPreferredSize(new java.awt.Dimension(110, 15));

        PP2.setLabelFor(PN1);
        PP2.setText("Price");

        PN3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PN3.setText("Product Name");

        PD3.setLabelFor(PN1);
        PD3.setText("<Product description>");
        PD3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PD3.setMaximumSize(new java.awt.Dimension(110, 15));
        PD3.setMinimumSize(new java.awt.Dimension(110, 15));
        PD3.setPreferredSize(new java.awt.Dimension(110, 15));

        PP3.setLabelFor(PN1);
        PP3.setText("Price");

        PN4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PN4.setText("Product Name");

        PD4.setLabelFor(PN1);
        PD4.setText("<Product description>");
        PD4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PD4.setMaximumSize(new java.awt.Dimension(110, 15));
        PD4.setMinimumSize(new java.awt.Dimension(110, 15));
        PD4.setPreferredSize(new java.awt.Dimension(110, 15));

        PP4.setLabelFor(PN1);
        PP4.setText("Price");

        PN5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PN5.setText("Product Name");

        PD5.setLabelFor(PN1);
        PD5.setText("<Product description>");
        PD5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PD5.setMaximumSize(new java.awt.Dimension(110, 15));
        PD5.setMinimumSize(new java.awt.Dimension(110, 15));
        PD5.setPreferredSize(new java.awt.Dimension(110, 15));

        PP5.setLabelFor(PN1);
        PP5.setText("Price");

        PN6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PN6.setText("Product Name");

        PD6.setLabelFor(PN1);
        PD6.setText("<Product description>");
        PD6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PD6.setMaximumSize(new java.awt.Dimension(110, 15));
        PD6.setMinimumSize(new java.awt.Dimension(110, 15));
        PD6.setPreferredSize(new java.awt.Dimension(110, 15));

        PP6.setLabelFor(PN1);
        PP6.setText("Price");

        PN7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PN7.setText("Product Name");

        PD7.setLabelFor(PN1);
        PD7.setText("<Product description>");
        PD7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PD7.setMaximumSize(new java.awt.Dimension(110, 15));
        PD7.setMinimumSize(new java.awt.Dimension(110, 15));
        PD7.setPreferredSize(new java.awt.Dimension(110, 15));

        PP7.setLabelFor(PN1);
        PP7.setText("Price");

        PN8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PN8.setText("Product Name");

        PD8.setLabelFor(PN1);
        PD8.setText("<Product description>");
        PD8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PD8.setMaximumSize(new java.awt.Dimension(110, 15));
        PD8.setMinimumSize(new java.awt.Dimension(110, 15));
        PD8.setPreferredSize(new java.awt.Dimension(110, 15));

        PP8.setLabelFor(PN1);
        PP8.setText("Price");

        org.jdesktop.layout.GroupLayout breakfastMenuPanelLayout = new org.jdesktop.layout.GroupLayout(breakfastMenuPanel);
        breakfastMenuPanel.setLayout(breakfastMenuPanelLayout);
        breakfastMenuPanelLayout.setHorizontalGroup(
            breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(breakfastMenuPanelLayout.createSequentialGroup()
                .add(breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(breakfastMenuPanelLayout.createSequentialGroup()
                            .add(PN7)
                            .add(102, 102, 102)
                            .add(PP7))
                        .add(PD7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(breakfastMenuPanelLayout.createSequentialGroup()
                            .add(PN6)
                            .add(102, 102, 102)
                            .add(PP6))
                        .add(PD6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(breakfastMenuPanelLayout.createSequentialGroup()
                                .add(21, 21, 21)
                                .add(PD8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, breakfastMenuPanelLayout.createSequentialGroup()
                                .add(PN8)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(PP8))))
                    .add(breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(breakfastMenuPanelLayout.createSequentialGroup()
                                    .add(21, 21, 21)
                                    .add(PD5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(breakfastMenuPanelLayout.createSequentialGroup()
                                    .add(PN5)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(PP5)))
                            .add(breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(breakfastMenuPanelLayout.createSequentialGroup()
                                    .add(21, 21, 21)
                                    .add(PD4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(breakfastMenuPanelLayout.createSequentialGroup()
                                    .add(PN4)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(PP4))))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, breakfastMenuPanelLayout.createSequentialGroup()
                                .add(PN2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(PP2))
                            .add(breakfastMenuPanelLayout.createSequentialGroup()
                                .add(21, 21, 21)
                                .add(PD2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(breakfastMenuPanelLayout.createSequentialGroup()
                                .add(21, 21, 21)
                                .add(PD3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, breakfastMenuPanelLayout.createSequentialGroup()
                                .add(PN3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(PP3)))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(breakfastMenuPanelLayout.createSequentialGroup()
                                .add(PN1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(PP1))
                            .add(breakfastMenuPanelLayout.createSequentialGroup()
                                .add(21, 21, 21)
                                .add(PD1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        breakfastMenuPanelLayout.setVerticalGroup(
            breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(breakfastMenuPanelLayout.createSequentialGroup()
                .add(breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(PN1)
                    .add(PP1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PD1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(PN2)
                    .add(PP2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PD2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PN3)
                    .add(PP3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PD3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PN4)
                    .add(PP4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PD4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PN5)
                    .add(PP5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PD5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(PN6)
                    .add(PP6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PD6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(breakfastMenuPanelLayout.createSequentialGroup()
                        .add(PP7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(PD7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(PN7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(breakfastMenuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PN8)
                    .add(PP8))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PD8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        breakfastMenuSP.setViewportView(breakfastMenuPanel);
        breakfastMenuPanel.getAccessibleContext().setAccessibleName("menuPanel");

        menuPanel.add(breakfastMenuSP, "card2");

        basketTable.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        basketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Qty.", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        basketTable.setFillsViewportHeight(true);
        basketTable.setMaximumSize(new java.awt.Dimension(500, 1000));
        basketTable.setMinimumSize(new java.awt.Dimension(225, 350));
        basketTable.setPreferredSize(new java.awt.Dimension(225, 350));
        basketTable.setRowHeight(20);
        basketTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        basketTable.setShowHorizontalLines(true);
        basketSP.setViewportView(basketTable);
        if (basketTable.getColumnModel().getColumnCount() > 0) {
            basketTable.getColumnModel().getColumn(0).setResizable(false);
            basketTable.getColumnModel().getColumn(0).setPreferredWidth(155);
            basketTable.getColumnModel().getColumn(1).setResizable(false);
            basketTable.getColumnModel().getColumn(1).setPreferredWidth(30);
            basketTable.getColumnModel().getColumn(2).setResizable(false);
            basketTable.getColumnModel().getColumn(2).setPreferredWidth(40);
        }

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel1.setText("Basket");

        org.jdesktop.layout.GroupLayout menuTabLayout = new org.jdesktop.layout.GroupLayout(menuTab);
        menuTab.setLayout(menuTabLayout);
        menuTabLayout.setHorizontalGroup(
            menuTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(menuTabLayout.createSequentialGroup()
                .add(menuTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(menuTabLayout.createSequentialGroup()
                        .add(breakfastSelect)
                        .add(18, 18, 18)
                        .add(lunchSelect)
                        .add(18, 18, 18)
                        .add(dinnerSelect)
                        .add(18, 18, 18)
                        .add(drinksSelect))
                    .add(menuTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(menuPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .add(menuTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(menuTabLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(basketSP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(menuTabLayout.createSequentialGroup()
                        .add(114, 114, 114)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(125, Short.MAX_VALUE))))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, menuTabLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(orderTotalCostLbl)
                .add(0, 0, 0)
                .add(orderTotalCostField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(orderBtn)
                .add(26, 26, 26))
        );
        menuTabLayout.setVerticalGroup(
            menuTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(menuTabLayout.createSequentialGroup()
                .addContainerGap()
                .add(menuTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(breakfastSelect)
                    .add(lunchSelect)
                    .add(dinnerSelect)
                    .add(drinksSelect)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(menuTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(basketSP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .add(menuPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 18, Short.MAX_VALUE)
                .add(menuTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(orderBtn)
                    .add(orderTotalCostField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(orderTotalCostLbl))
                .addContainerGap())
        );

        clientTabs.addTab("Menu", menuTab);
        menuTab.getAccessibleContext().setAccessibleName("MenuTab");
        menuTab.getAccessibleContext().setAccessibleParent(this);

        orderHistoryTable.setAutoCreateRowSorter(true);
        orderHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "Date", "Time", "Contents", "Cost", "Refund"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderHistoryTable.setColumnSelectionAllowed(true);
        orderHistoryTable.getTableHeader().setReorderingAllowed(false);
        orderHistoryScrollPanel.setViewportView(orderHistoryTable);
        orderHistoryTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (orderHistoryTable.getColumnModel().getColumnCount() > 0) {
            orderHistoryTable.getColumnModel().getColumn(0).setResizable(false);
        }
        orderHistoryTable.getAccessibleContext().setAccessibleParent(orderHistoryTab);

        totalSpentLbl.setText("Total amount spent");

        totalSpentField.setEditable(false);
        totalSpentField.setColumns(4);
        totalSpentField.setText("1450");
        totalSpentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalSpentFieldActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout orderHistoryTabLayout = new org.jdesktop.layout.GroupLayout(orderHistoryTab);
        orderHistoryTab.setLayout(orderHistoryTabLayout);
        orderHistoryTabLayout.setHorizontalGroup(
            orderHistoryTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(orderHistoryTabLayout.createSequentialGroup()
                .addContainerGap()
                .add(orderHistoryScrollPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, orderHistoryTabLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(totalSpentLbl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(totalSpentField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(45, 45, 45))
        );
        orderHistoryTabLayout.setVerticalGroup(
            orderHistoryTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(orderHistoryTabLayout.createSequentialGroup()
                .addContainerGap()
                .add(orderHistoryScrollPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 406, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(orderHistoryTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(totalSpentLbl)
                    .add(totalSpentField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        clientTabs.addTab("Order History", orderHistoryTab);

        accountTab.setEnabled(false);

        accountManagerSelect.add(accountChangeEmailSelect);
        accountChangeEmailSelect.setText("Change Email");
        accountChangeEmailSelect.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                accountChangeEmailSelectStateChanged(evt);
            }
        });
        accountChangeEmailSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountChangeEmailSelectActionPerformed(evt);
            }
        });

        accountManagerSelect.add(accountChangePassSelect);
        accountChangePassSelect.setText("Change Password");
        accountChangePassSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountChangePassSelectActionPerformed(evt);
            }
        });

        accountPassLbl.setText("<html>Current<br>password");

        accountPassField.setEnabled(false);
        accountPassField.setMinimumSize(new java.awt.Dimension(150, 28));
        accountPassField.setPreferredSize(new java.awt.Dimension(150, 28));
        accountPassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accountPassFieldKeyTyped(evt);
            }
        });

        accountNewEmailLbl.setText("New Email");

        accountNewEmailField.setEnabled(false);
        accountNewEmailField.setMinimumSize(new java.awt.Dimension(150, 28));
        accountNewEmailField.setPreferredSize(new java.awt.Dimension(150, 28));
        accountNewEmailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accountNewEmailFieldKeyTyped(evt);
            }
        });

        accountChangeEmailBtn.setText("Change Email");
        accountChangeEmailBtn.setEnabled(false);
        accountChangeEmailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountChangeEmailBtnActionPerformed(evt);
            }
        });

        accountOldPassLbl.setText("<html>Current<br>password");

        accountOldPassField.setEnabled(false);
        accountOldPassField.setMinimumSize(new java.awt.Dimension(150, 28));
        accountOldPassField.setPreferredSize(new java.awt.Dimension(150, 28));
        accountOldPassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accountOldPassFieldKeyTyped(evt);
            }
        });

        accountNewPassLbl.setText("New password");

        accountNewPassField.setEnabled(false);
        accountNewPassField.setMinimumSize(new java.awt.Dimension(150, 28));
        accountNewPassField.setName("accountNewPass"); // NOI18N
        accountNewPassField.setPreferredSize(new java.awt.Dimension(150, 28));
        accountNewPassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accountNewPassFieldKeyTyped(evt);
            }
        });

        accountNewPass2Lbl.setText("<html>Repreat new<br>password");

        accountNewPass2Field.setEnabled(false);
        accountNewPass2Field.setMinimumSize(new java.awt.Dimension(150, 28));
        accountNewPass2Field.setName("repeatPass"); // NOI18N
        accountNewPass2Field.setPreferredSize(new java.awt.Dimension(150, 28));
        accountNewPass2Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accountNewPass2FieldKeyTyped(evt);
            }
        });

        accountChangePassBtn.setText("Change Password");
        accountChangePassBtn.setEnabled(false);
        accountChangePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountChangePassBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout accountTabLayout = new org.jdesktop.layout.GroupLayout(accountTab);
        accountTab.setLayout(accountTabLayout);
        accountTabLayout.setHorizontalGroup(
            accountTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, accountTabLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .add(accountTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(accountTabLayout.createSequentialGroup()
                        .add(284, 284, 284)
                        .add(accountChangePassSelect))
                    .add(accountTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(accountChangePassBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 196, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(accountTabLayout.createSequentialGroup()
                            .add(accountTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(accountTabLayout.createSequentialGroup()
                                    .add(accountChangeEmailSelect)
                                    .add(134, 134, 134))
                                .add(accountTabLayout.createSequentialGroup()
                                    .add(accountTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(accountTabLayout.createSequentialGroup()
                                            .add(accountPassLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                            .add(accountPassField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(accountTabLayout.createSequentialGroup()
                                            .add(accountNewEmailLbl)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                            .add(accountNewEmailField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(accountChangeEmailBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 196, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(30, 30, 30)))
                            .add(accountTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(accountTabLayout.createSequentialGroup()
                                    .add(13, 13, 13)
                                    .add(accountTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                        .add(accountOldPassLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(accountNewPass2Lbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                .add(accountNewPassLbl))
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                            .add(accountTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(accountNewPass2Field, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(accountNewPassField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(accountOldPassField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .add(41, 41, 41))
        );
        accountTabLayout.setVerticalGroup(
            accountTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(accountTabLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(accountTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(accountChangeEmailSelect)
                    .add(accountChangePassSelect))
                .add(18, 18, 18)
                .add(accountTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(accountTabLayout.createSequentialGroup()
                        .add(accountTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(accountOldPassLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(accountOldPassField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(accountPassLbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(accountPassField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(accountTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(accountNewPassField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(accountNewPassLbl)
                            .add(accountNewEmailField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(accountNewEmailLbl))
                        .add(18, 18, 18)
                        .add(accountNewPass2Field, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(accountNewPass2Lbl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(accountTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(accountChangePassBtn)
                    .add(accountChangeEmailBtn))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clientTabs.addTab("Manage Account", accountTab);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(clientTabs, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(clientTabs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 500, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        clientTabs.getAccessibleContext().setAccessibleName("TabPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bankPaySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankPaySelectActionPerformed
        ((CardLayout)orderPayPanel.getLayout()).show(orderPayPanel, "bankPay");
        System.out.println("Switching..");
    }//GEN-LAST:event_bankPaySelectActionPerformed

    private void cardPaySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardPaySelectActionPerformed
        ((CardLayout)orderPayPanel.getLayout()).show(orderPayPanel, "cardPay");
    }//GEN-LAST:event_cardPaySelectActionPerformed

    private void cardNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNoFieldActionPerformed

    private void orderBtnCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnCardActionPerformed
        JOptionPane.showMessageDialog(
                orderDialog,
                "Your order has been successfully placed.",
                "Order confirmation",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_orderBtnCardActionPerformed

    private void orderPayPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_orderPayPanelComponentShown
        //evt.getComponent().doLayout();
    }//GEN-LAST:event_orderPayPanelComponentShown

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
        orderDialog.setVisible(true);
        paymentTotalCostField.setText(orderTotalCostField.getText());
    }//GEN-LAST:event_orderBtnActionPerformed

    private void bankAccNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankAccNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankAccNoFieldActionPerformed

    private void accountChangeEmailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountChangeEmailBtnActionPerformed
        String email = accountNewEmailField.getText();
        if (user.setEmail(email, accountPassField.getText().getBytes()))
            JOptionPane.showMessageDialog(
                        this,
                        "Your email has been successfully changed.",
                        "Change successful",
                        JOptionPane.INFORMATION_MESSAGE);
        else 
            JOptionPane.showMessageDialog(
                        this,
                        "The password you provided does not match. Please try again.",
                        "Change unsuccesful",
                        JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_accountChangeEmailBtnActionPerformed

    private void accountChangePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountChangePassBtnActionPerformed
        if (user.setPassword(
                accountOldPassField.getText().getBytes(),
                accountNewPassField.getText().getBytes()))
            JOptionPane.showMessageDialog(
                        this,
                        "Your password has been successfully changed.",
                        "Change successful",
                        JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(
                        this,
                        "The password you provided does not match. Please try again.",
                        "Change unsuccesful",
                        JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_accountChangePassBtnActionPerformed

    private void accountChangeEmailSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountChangeEmailSelectActionPerformed
        pv.setBypass(true);
        pv.hidePopup();
        pvRepeat.setBypass(true);
        pvRepeat.hidePopup();
        ev.setBypass(false);
        accountOldPassField.setEnabled(false);
        accountNewPassField.setEnabled(false);
        accountNewPass2Field.setEnabled(false);
        accountChangePassBtn.setEnabled(false);
        accountPassField.setEnabled(true);
        if (!accountPassField.getText().equals(""))
        {
            accountNewEmailField.setEnabled(true);
        }
    }//GEN-LAST:event_accountChangeEmailSelectActionPerformed

    private void accountChangePassSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountChangePassSelectActionPerformed
        ev.setBypass(true);
        ev.hidePopup();
        pv.setBypass(false);
        pvRepeat.setBypass(false);
        accountNewEmailField.setEnabled(false);
        accountPassField.setEnabled(false);
        accountChangeEmailBtn.setEnabled(false);
        accountOldPassField.setEnabled(true);
        if (!accountOldPassField.getText().equals(""))
        {
            accountNewPassField.setEnabled(true);
            if (!accountNewPassField.getText().equals(""))
                accountNewPass2Field.setEnabled(true);
        }
    }//GEN-LAST:event_accountChangePassSelectActionPerformed

    private void accountChangeEmailSelectStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_accountChangeEmailSelectStateChanged
        
    }//GEN-LAST:event_accountChangeEmailSelectStateChanged

    private void totalSpentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalSpentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalSpentFieldActionPerformed

    private void priorityBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorityBoxActionPerformed
        float total = Float.parseFloat(paymentTotalCostField.getText());
        if (priorityBox.isSelected())
        {
            total += (total/20);
        } else total -= (total/20);
        paymentTotalCostField.setText(Float.toString(total));
    }//GEN-LAST:event_priorityBoxActionPerformed

    private void paymentTotalCostFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentTotalCostFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentTotalCostFieldActionPerformed

    private void orderBtnBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnBankActionPerformed
        JOptionPane.showMessageDialog(
                orderDialog,
                "Your order has been successfully placed.",
                "Order confirmation",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_orderBtnBankActionPerformed

    private void accountPassFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountPassFieldKeyTyped
        accountNewEmailField.setEnabled(true);
    }//GEN-LAST:event_accountPassFieldKeyTyped

    private void accountOldPassFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountOldPassFieldKeyTyped
        accountNewPassField.setEnabled(true);
    }//GEN-LAST:event_accountOldPassFieldKeyTyped

    private void accountNewEmailFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountNewEmailFieldKeyTyped
        accountChangeEmailBtn.setEnabled(true);
    }//GEN-LAST:event_accountNewEmailFieldKeyTyped

    private void accountNewPass2FieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountNewPass2FieldKeyTyped
        accountChangePassBtn.setEnabled(true);
    }//GEN-LAST:event_accountNewPass2FieldKeyTyped

    private void accountNewPassFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountNewPassFieldKeyTyped
        accountNewPass2Field.setEnabled(true);
    }//GEN-LAST:event_accountNewPassFieldKeyTyped

    private void PN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PN1ActionPerformed
        if (PN1.isSelected())
        {
            basket.add(bfMenu.getProduct(0));
            orderTotalCostField.setText(Integer.toString(basket.getTotal()));
            //basket code goes here too
        } else 
        {
            basket.remove(bfMenu.getProduct(0));
            orderTotalCostField.setText(Integer.toString(basket.getTotal()));
        }
    }//GEN-LAST:event_PN1ActionPerformed

    private void orderTotalCostFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderTotalCostFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderTotalCostFieldActionPerformed

    private void PN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PN2ActionPerformed
        if (PN2.isSelected())
        {
            basket.add(bfMenu.getProduct(1));
            orderTotalCostField.setText(Integer.toString(basket.getTotal()));
        } else 
        {
            basket.remove(bfMenu.getProduct(1));
            orderTotalCostField.setText(Integer.toString(basket.getTotal()));
        }
    }//GEN-LAST:event_PN2ActionPerformed

    private void homeLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeLogoutBtnActionPerformed
        int logoutOpt = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to log out?",
                "Log out confirmation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (logoutOpt == 0)
        {
            user.logout();
            dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        } else System.out.println("no?");
    }//GEN-LAST:event_homeLogoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientWindow(conn, user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CardExpDateLbl;
    private javax.swing.JLabel PD1;
    private javax.swing.JLabel PD2;
    private javax.swing.JLabel PD3;
    private javax.swing.JLabel PD4;
    private javax.swing.JLabel PD5;
    private javax.swing.JLabel PD6;
    private javax.swing.JLabel PD7;
    private javax.swing.JLabel PD8;
    private javax.swing.JCheckBox PN1;
    private javax.swing.JCheckBox PN2;
    private javax.swing.JCheckBox PN3;
    private javax.swing.JCheckBox PN4;
    private javax.swing.JCheckBox PN5;
    private javax.swing.JCheckBox PN6;
    private javax.swing.JCheckBox PN7;
    private javax.swing.JCheckBox PN8;
    private javax.swing.JLabel PP1;
    private javax.swing.JLabel PP2;
    private javax.swing.JLabel PP3;
    private javax.swing.JLabel PP4;
    private javax.swing.JLabel PP5;
    private javax.swing.JLabel PP6;
    private javax.swing.JLabel PP7;
    private javax.swing.JLabel PP8;
    private javax.swing.JButton accountChangeEmailBtn;
    private javax.swing.JRadioButton accountChangeEmailSelect;
    private javax.swing.JButton accountChangePassBtn;
    private javax.swing.JRadioButton accountChangePassSelect;
    private javax.swing.ButtonGroup accountManagerSelect;
    private javax.swing.JTextField accountNewEmailField;
    private javax.swing.JLabel accountNewEmailLbl;
    private javax.swing.JPasswordField accountNewPass2Field;
    private javax.swing.JLabel accountNewPass2Lbl;
    private javax.swing.JPasswordField accountNewPassField;
    private javax.swing.JLabel accountNewPassLbl;
    private javax.swing.JPasswordField accountOldPassField;
    private javax.swing.JLabel accountOldPassLbl;
    private javax.swing.JPasswordField accountPassField;
    private javax.swing.JLabel accountPassLbl;
    private javax.swing.JPanel accountTab;
    private javax.swing.JTextField bankAccNameField;
    private javax.swing.JLabel bankAccNameLbl;
    private javax.swing.JTextField bankAccNoField;
    private javax.swing.JLabel bankAccNoLbl;
    private javax.swing.JPanel bankPayPanel;
    private javax.swing.JRadioButton bankPaySelect;
    private javax.swing.JTextField bankSortCodeF1;
    private javax.swing.JTextField bankSortCodeF2;
    private javax.swing.JTextField bankSortCodeF3;
    private javax.swing.JLabel bankSortCodeLbl;
    private javax.swing.JScrollPane basketSP;
    private javax.swing.JTable basketTable;
    private javax.swing.JPanel breakfastMenuPanel;
    private javax.swing.JScrollPane breakfastMenuSP;
    private javax.swing.JRadioButton breakfastSelect;
    private javax.swing.JTextField cardCodeField;
    private javax.swing.JLabel cardCodeLbl;
    private javax.swing.JComboBox cardMonthBox;
    private javax.swing.JTextField cardNameField;
    private javax.swing.JLabel cardNameLbl;
    private javax.swing.JTextField cardNoField;
    private javax.swing.JLabel cardNoLbl;
    private javax.swing.JPanel cardPayPanel;
    private javax.swing.JRadioButton cardPaySelect;
    private javax.swing.JComboBox cardTypeBox;
    private javax.swing.JLabel cardTypeLbl;
    private javax.swing.JComboBox cardYearBox;
    private javax.swing.JTabbedPane clientTabs;
    private javax.swing.JRadioButton dinnerSelect;
    private javax.swing.JRadioButton drinksSelect;
    private javax.swing.JTextField homeDiscountPlanField;
    private javax.swing.JLabel homeDiscountPlanLbl;
    private javax.swing.JButton homeLogoutBtn;
    private javax.swing.JTextField homeNextStatusField;
    private javax.swing.JLabel homeNextStatusLbl;
    private javax.swing.JPanel homeTab;
    private javax.swing.JTextField homeVIPStatusField;
    private javax.swing.JLabel homeVIPStatusLbl;
    private javax.swing.JLabel homeWelcomeLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton lunchSelect;
    private javax.swing.JPanel menuPanel;
    private javax.swing.ButtonGroup menuSelector;
    private javax.swing.JPanel menuTab;
    private javax.swing.JButton orderBtn;
    private javax.swing.JButton orderBtnBank;
    private javax.swing.JButton orderBtnCard;
    private javax.swing.JPanel orderBtnPanel;
    private javax.swing.JDialog orderDialog;
    private javax.swing.JScrollPane orderHistoryScrollPanel;
    private javax.swing.JPanel orderHistoryTab;
    private javax.swing.JTable orderHistoryTable;
    private javax.swing.JPanel orderPayPanel;
    private javax.swing.JTextField orderTotalCostField;
    private javax.swing.JLabel orderTotalCostLbl;
    private javax.swing.ButtonGroup payTypeSelector;
    private javax.swing.JTextField paymentTotalCostField;
    private javax.swing.JLabel paymentTotalCostLbl;
    private javax.swing.JCheckBox priorityBox;
    private javax.swing.JTextField totalSpentField;
    private javax.swing.JLabel totalSpentLbl;
    // End of variables declaration//GEN-END:variables
}
