/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CoD.gui;

import CoD.DBConnect;
import CoD.User;
import java.awt.CardLayout;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Stefan
 */
public class ManagerWindow extends javax.swing.JFrame {
    private static DBConnect    conn;
    private static User         user;
    private String              reportType = "Staff performance";

    /**
     * Creates new form ManagerWindow
     * @param conn
     * @param user
     */    
    public ManagerWindow(DBConnect conn, User user) {
        initComponents();
        this.conn = conn;
        this.user = user;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        discountSelector = new javax.swing.ButtonGroup();
        reportFrame = new javax.swing.JFrame();
        reportSearchLbl = new javax.swing.JLabel();
        reportSearchField = new javax.swing.JTextField();
        reportPrintBtn = new javax.swing.JButton();
        reportsPanel = new javax.swing.JPanel();
        staffPerformanceReportSP = new javax.swing.JScrollPane();
        staffPerformanceReportTable = new javax.swing.JTable();
        customersLoggedInReportSP = new javax.swing.JScrollPane();
        usersLoggedInReportTable = new javax.swing.JTable();
        ordersReportSP = new javax.swing.JScrollPane();
        ordersReportTable = new javax.swing.JTable();
        refundReportSP = new javax.swing.JScrollPane();
        refundReportTable = new javax.swing.JTable();
        customerSpendingReportSP = new javax.swing.JScrollPane();
        customerSpendingReportTable = new javax.swing.JTable();
        managerTabs = new javax.swing.JTabbedPane();
        updateStockTab = new javax.swing.JPanel();
        productsScroll = new javax.swing.JScrollPane();
        productsList = new javax.swing.JList();
        quantityField = new javax.swing.JTextField();
        quantityLbl = new javax.swing.JLabel();
        updateStockBtn = new javax.swing.JButton();
        manageMenuTab = new javax.swing.JPanel();
        menuItemsScroll = new javax.swing.JScrollPane();
        menuItemsList = new javax.swing.JList();
        editNameLbl = new javax.swing.JLabel();
        editNameField = new javax.swing.JTextField();
        editDescriptionLbl = new javax.swing.JLabel();
        editDescriptionScroll = new javax.swing.JScrollPane();
        editDescriptionArea = new javax.swing.JTextArea();
        editDurationLbl = new javax.swing.JLabel();
        editDurationField = new javax.swing.JTextField();
        editPriceLbl = new javax.swing.JLabel();
        editPriceField = new javax.swing.JTextField();
        editTypeLbl = new javax.swing.JLabel();
        editTypeBox = new javax.swing.JComboBox();
        isAvailableBox = new javax.swing.JCheckBox();
        dailySpecialLbl = new javax.swing.JLabel();
        dailySpecialBox = new javax.swing.JComboBox();
        updateItemBtn = new javax.swing.JButton();
        deleteItemBtn = new javax.swing.JButton();
        addItemBtn = new javax.swing.JButton();
        reportsAndRefundsTab = new javax.swing.JPanel();
        reportTypeLbl = new javax.swing.JLabel();
        reportTypeBox = new javax.swing.JComboBox();
        reportFromLbl = new javax.swing.JLabel();
        reportFromField = new javax.swing.JTextField();
        reportToLbl = new javax.swing.JLabel();
        reportToField = new javax.swing.JTextField();
        reportGenerateBtn = new javax.swing.JButton();
        refundTitleLbl = new javax.swing.JLabel();
        reportsAndRefundsSeparator = new javax.swing.JSeparator();
        refundPaymentIDLbl = new javax.swing.JLabel();
        refundPaymentIDField = new javax.swing.JTextField();
        refundRecordBtn = new javax.swing.JButton();
        discountsTab = new javax.swing.JPanel();
        vipCustomerScroll = new javax.swing.JScrollPane();
        vipCustomersList = new javax.swing.JList();
        fixedDiscountBtn = new javax.swing.JRadioButton();
        fixedDiscountField = new javax.swing.JTextField();
        flexibleDiscountBtn = new javax.swing.JRadioButton();
        flexibleDiscountBox = new javax.swing.JComboBox();
        setDiscountBtn = new javax.swing.JButton();
        VIPSilverStatusLbl = new javax.swing.JLabel();
        VIPSilverStatusField = new javax.swing.JTextField();
        VIPGoldStatusLbl = new javax.swing.JLabel();
        VIPGoldStatusField = new javax.swing.JTextField();
        VIPDiamondStatusLbl = new javax.swing.JLabel();
        VIPDiamondStatusField = new javax.swing.JTextField();
        accountsTab = new javax.swing.JPanel();
        accountsSelectLbl = new javax.swing.JLabel();
        accountsSelectBox = new javax.swing.JComboBox();
        nameLbl = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        surnameLbl = new javax.swing.JLabel();
        surnameField = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        accountTypeLbl = new javax.swing.JLabel();
        accountTypeBox = new javax.swing.JComboBox();
        accountAddBtn = new javax.swing.JButton();
        accountUpdateBtn = new javax.swing.JButton();
        accountDeleteBtn = new javax.swing.JButton();

        reportFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        reportFrame.setTitle("Generated report");
        reportFrame.setMinimumSize(new java.awt.Dimension(500, 360));

        reportSearchLbl.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        reportSearchLbl.setText("Search");

        reportPrintBtn.setText("Print");

        reportsPanel.setLayout(new java.awt.CardLayout());

        staffPerformanceReportSP.setPreferredSize(new java.awt.Dimension(456, 200));

        staffPerformanceReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "EmployeeID", "Breakfast orders", "Lunch orders", "Dinner orders", "Breakfast min time", "Breakfast max time", "Lunch min time", "Lunch max time", "Dinner min time", "Dinner max time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        staffPerformanceReportTable.setShowHorizontalLines(true);
        staffPerformanceReportTable.setShowVerticalLines(true);
        staffPerformanceReportSP.setViewportView(staffPerformanceReportTable);

        reportsPanel.add(staffPerformanceReportSP, "Staff performance");
        staffPerformanceReportSP.getAccessibleContext().setAccessibleDescription("");

        usersLoggedInReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CustomerID", "Customer name", "Customer surname", "OrderID", "Order date", "Order time", "Order priority", "Order status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usersLoggedInReportTable.setShowHorizontalLines(true);
        usersLoggedInReportTable.setShowVerticalLines(true);
        customersLoggedInReportSP.setViewportView(usersLoggedInReportTable);

        reportsPanel.add(customersLoggedInReportSP, "Customers logged in");

        ordersReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CustomerID", "Customer name", "Customer surname", "OrderID", "Order date", "Order time", "Order priority", "Order status", "EmployeeID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ordersReportTable.setShowHorizontalLines(true);
        ordersReportTable.setShowVerticalLines(true);
        ordersReportSP.setViewportView(ordersReportTable);

        reportsPanel.add(ordersReportSP, "Individual orders");

        refundReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PaymentID", "Refund date", "Refund time", "ManagerID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        refundReportTable.setShowHorizontalLines(true);
        refundReportTable.setShowVerticalLines(true);
        refundReportSP.setViewportView(refundReportTable);

        reportsPanel.add(refundReportSP, "Refunds");

        customerSpendingReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CustomerID", "Customer name", "Customer surname", "Amount spent"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerSpendingReportTable.setShowHorizontalLines(true);
        customerSpendingReportTable.setShowVerticalLines(true);
        customerSpendingReportSP.setViewportView(customerSpendingReportTable);

        reportsPanel.add(customerSpendingReportSP, "Customer spending");

        javax.swing.GroupLayout reportFrameLayout = new javax.swing.GroupLayout(reportFrame.getContentPane());
        reportFrame.getContentPane().setLayout(reportFrameLayout);
        reportFrameLayout.setHorizontalGroup(
            reportFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reportPrintBtn))
                    .addComponent(reportsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(reportFrameLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(reportSearchLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reportFrameLayout.setVerticalGroup(
            reportFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportSearchLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reportPrintBtn)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(365, 535));
        setName("managerFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(365, 535));

        managerTabs.setMinimumSize(new java.awt.Dimension(360, 515));
        managerTabs.setPreferredSize(new java.awt.Dimension(360, 515));

        updateStockTab.setMinimumSize(new java.awt.Dimension(360, 500));
        updateStockTab.setPreferredSize(new java.awt.Dimension(360, 500));

        productsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Product Name1", "Product Name2", "Product Name3", "Product Name4", "Product Name5", "Product Name6", "Product Name7", "Product Name8", "Product Name9", "Product Name10" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        productsList.setMaximumSize(new java.awt.Dimension(170, 100));
        productsList.setMinimumSize(new java.awt.Dimension(170, 100));
        productsList.setPreferredSize(new java.awt.Dimension(170, 100));
        productsList.setSelectionBackground(new java.awt.Color(0, 153, 153));
        productsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsListMouseClicked(evt);
            }
        });
        productsScroll.setViewportView(productsList);

        quantityField.setEnabled(false);
        quantityField.setMinimumSize(new java.awt.Dimension(35, 28));
        quantityField.setPreferredSize(new java.awt.Dimension(35, 28));
        quantityField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quantityFieldKeyPressed(evt);
            }
        });

        quantityLbl.setText("Increase Stock by");

        updateStockBtn.setText("Update");
        updateStockBtn.setEnabled(false);

        javax.swing.GroupLayout updateStockTabLayout = new javax.swing.GroupLayout(updateStockTab);
        updateStockTab.setLayout(updateStockTabLayout);
        updateStockTabLayout.setHorizontalGroup(
            updateStockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateStockTabLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(updateStockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(updateStockTabLayout.createSequentialGroup()
                        .addComponent(quantityLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateStockBtn)))
                .addGap(97, 97, 97))
        );
        updateStockTabLayout.setVerticalGroup(
            updateStockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateStockTabLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(productsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updateStockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateStockBtn)
                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityLbl))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        managerTabs.addTab("Update Stock", updateStockTab);

        manageMenuTab.setMinimumSize(new java.awt.Dimension(360, 500));
        manageMenuTab.setPreferredSize(new java.awt.Dimension(360, 500));

        menuItemsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        menuItemsList.setMaximumSize(new java.awt.Dimension(170, 220));
        menuItemsList.setMinimumSize(new java.awt.Dimension(170, 220));
        menuItemsList.setPreferredSize(new java.awt.Dimension(170, 220));
        menuItemsList.setSelectionBackground(new java.awt.Color(0, 153, 153));
        menuItemsScroll.setViewportView(menuItemsList);

        editNameLbl.setText("Name");

        editNameField.setText("< selected product name>");

        editDescriptionLbl.setText("Description");

        editDescriptionArea.setColumns(19);
        editDescriptionArea.setRows(4);
        editDescriptionArea.setTabSize(1);
        editDescriptionArea.setText("<selected product description>");
        editDescriptionScroll.setViewportView(editDescriptionArea);

        editDurationLbl.setText("<html>Intended<br>duration");

        editDurationField.setText("<duration>");

        editPriceLbl.setText("Price");

        editPriceField.setText("<price>");

        editTypeLbl.setText("Type");

        editTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Breakfast", "Lunch", "Dinner", "Special", "Breakfast hot drink", "Breakfast cold drink", "Lunch hot drink", "Lunch cold drink", "Lunch starter", "Lunch dessert", "Dinner hot drink", "Dinner cold drink", "Dinner starter", "Dinner dessert" }));

        isAvailableBox.setText("Available");
        isAvailableBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isAvailableBoxActionPerformed(evt);
            }
        });

        dailySpecialLbl.setText("Daily special");

        dailySpecialBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Special 1", "Special 2", "Special 3", "Special 4", "Special 5", "Special 6", "Special 7" }));

        updateItemBtn.setText("Update");

        deleteItemBtn.setText("Delete");
        deleteItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemBtnActionPerformed(evt);
            }
        });

        addItemBtn.setText("Add");

        javax.swing.GroupLayout manageMenuTabLayout = new javax.swing.GroupLayout(manageMenuTab);
        manageMenuTab.setLayout(manageMenuTabLayout);
        manageMenuTabLayout.setHorizontalGroup(
            manageMenuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageMenuTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageMenuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dailySpecialLbl)
                    .addComponent(editDescriptionLbl)
                    .addComponent(editNameLbl)
                    .addComponent(editDurationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editTypeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageMenuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageMenuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(manageMenuTabLayout.createSequentialGroup()
                            .addComponent(editDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(editPriceLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(editPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(manageMenuTabLayout.createSequentialGroup()
                            .addComponent(editTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(isAvailableBox))
                        .addGroup(manageMenuTabLayout.createSequentialGroup()
                            .addComponent(updateItemBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(deleteItemBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(addItemBtn))
                        .addComponent(menuItemsScroll)
                        .addComponent(editNameField)
                        .addComponent(editDescriptionScroll))
                    .addComponent(dailySpecialBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        manageMenuTabLayout.setVerticalGroup(
            manageMenuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageMenuTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuItemsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageMenuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editNameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageMenuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editDescriptionLbl)
                    .addComponent(editDescriptionScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageMenuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(manageMenuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editDurationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editPriceLbl)
                        .addComponent(editPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(editDurationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageMenuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editTypeLbl)
                    .addComponent(editTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isAvailableBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(manageMenuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dailySpecialLbl)
                    .addComponent(dailySpecialBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageMenuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateItemBtn)
                    .addComponent(deleteItemBtn)
                    .addComponent(addItemBtn))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        managerTabs.addTab("Manage Menu", manageMenuTab);

        reportTypeLbl.setText("<html>Type of report<br>to generate");

        reportTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Staff performance", "Customer spending", "Customers logged in", "Individual orders", "Refunds" }));
        reportTypeBox.setMinimumSize(new java.awt.Dimension(165, 26));
        reportTypeBox.setPreferredSize(new java.awt.Dimension(165, 26));
        reportTypeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportTypeBoxActionPerformed(evt);
            }
        });

        reportFromLbl.setText("From");

        reportFromField.setText("dd.mm.yyyy");
        reportFromField.setToolTipText("");
        reportFromField.setMinimumSize(new java.awt.Dimension(75, 28));
        reportFromField.setPreferredSize(new java.awt.Dimension(75, 28));
        reportFromField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportFromFieldActionPerformed(evt);
            }
        });

        reportToLbl.setText("To");

        reportToField.setText("dd.mm.yyyy");
        reportToField.setMinimumSize(new java.awt.Dimension(75, 28));
        reportToField.setPreferredSize(new java.awt.Dimension(75, 28));

        reportGenerateBtn.setText("Generate");
        reportGenerateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportGenerateBtnActionPerformed(evt);
            }
        });

        refundTitleLbl.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        refundTitleLbl.setText("Record a refund");

        refundPaymentIDLbl.setText("PaymentID");

        refundRecordBtn.setText("Record");
        refundRecordBtn.setMaximumSize(new java.awt.Dimension(79, 28));
        refundRecordBtn.setMinimumSize(new java.awt.Dimension(79, 28));
        refundRecordBtn.setPreferredSize(new java.awt.Dimension(79, 28));
        refundRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refundRecordBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reportsAndRefundsTabLayout = new javax.swing.GroupLayout(reportsAndRefundsTab);
        reportsAndRefundsTab.setLayout(reportsAndRefundsTabLayout);
        reportsAndRefundsTabLayout.setHorizontalGroup(
            reportsAndRefundsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsAndRefundsTabLayout.createSequentialGroup()
                .addComponent(reportsAndRefundsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(reportsAndRefundsTabLayout.createSequentialGroup()
                .addGroup(reportsAndRefundsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportsAndRefundsTabLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(reportsAndRefundsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reportTypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportFromLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reportToLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(reportsAndRefundsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reportGenerateBtn)
                            .addComponent(reportFromField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportToField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(reportsAndRefundsTabLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(reportsAndRefundsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(refundTitleLbl)
                            .addGroup(reportsAndRefundsTabLayout.createSequentialGroup()
                                .addComponent(refundPaymentIDLbl)
                                .addGap(18, 18, 18)
                                .addGroup(reportsAndRefundsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(refundPaymentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(refundRecordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reportsAndRefundsTabLayout.setVerticalGroup(
            reportsAndRefundsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsAndRefundsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportsAndRefundsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reportTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportTypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(reportsAndRefundsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportFromField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportFromLbl))
                .addGap(18, 18, 18)
                .addGroup(reportsAndRefundsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportToLbl)
                    .addComponent(reportToField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reportGenerateBtn)
                .addGap(8, 8, 8)
                .addComponent(reportsAndRefundsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refundTitleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reportsAndRefundsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refundPaymentIDLbl)
                    .addComponent(refundPaymentIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(refundRecordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        managerTabs.addTab("Reports & Refunds", reportsAndRefundsTab);

        discountsTab.setMinimumSize(new java.awt.Dimension(360, 500));
        discountsTab.setPreferredSize(new java.awt.Dimension(360, 500));

        vipCustomersList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "VIP Customer 1", "VIP Customer 2", "VIP Customer 3", "VIP Customer 4", "VIP Customer 5", "VIP Customer 6", "VIP Customer 7", "VIP Customer 9", "VIP Customer 10", " ", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        vipCustomersList.setMaximumSize(new java.awt.Dimension(170, 220));
        vipCustomersList.setMinimumSize(new java.awt.Dimension(170, 220));
        vipCustomersList.setPreferredSize(new java.awt.Dimension(170, 220));
        vipCustomersList.setSelectionBackground(new java.awt.Color(0, 153, 153));
        vipCustomersList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vipCustomersListMouseClicked(evt);
            }
        });
        vipCustomerScroll.setViewportView(vipCustomersList);

        discountSelector.add(fixedDiscountBtn);
        fixedDiscountBtn.setText("Fixed discount (%)");
        fixedDiscountBtn.setEnabled(false);
        fixedDiscountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixedDiscountBtnActionPerformed(evt);
            }
        });

        fixedDiscountField.setEnabled(false);
        fixedDiscountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fixedDiscountFieldKeyTyped(evt);
            }
        });

        discountSelector.add(flexibleDiscountBtn);
        flexibleDiscountBtn.setText("Flexible discount");
        flexibleDiscountBtn.setEnabled(false);
        flexibleDiscountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flexibleDiscountBtnActionPerformed(evt);
            }
        });

        flexibleDiscountBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1-3%", "3-6%", "6-9%", "9-12%", "12-15%" }));
        flexibleDiscountBox.setEnabled(false);
        flexibleDiscountBox.setPreferredSize(new java.awt.Dimension(78, 26));

        setDiscountBtn.setText("Set discount");
        setDiscountBtn.setEnabled(false);

        VIPSilverStatusLbl.setText("Silver status threshold");

        VIPSilverStatusField.setColumns(4);
        VIPSilverStatusField.setText("1000");

        VIPGoldStatusLbl.setText("Gold status threshold");

        VIPGoldStatusField.setColumns(4);
        VIPGoldStatusField.setText("2000");

        VIPDiamondStatusLbl.setText("Diamond status threshold");

        VIPDiamondStatusField.setColumns(4);
        VIPDiamondStatusField.setText("5000");

        javax.swing.GroupLayout discountsTabLayout = new javax.swing.GroupLayout(discountsTab);
        discountsTab.setLayout(discountsTabLayout);
        discountsTabLayout.setHorizontalGroup(
            discountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discountsTabLayout.createSequentialGroup()
                .addGroup(discountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(discountsTabLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(vipCustomerScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, discountsTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(discountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(discountsTabLayout.createSequentialGroup()
                                .addGroup(discountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fixedDiscountBtn)
                                    .addComponent(flexibleDiscountBtn)
                                    .addGroup(discountsTabLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(setDiscountBtn)))
                                .addGap(18, 18, 18)
                                .addGroup(discountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(flexibleDiscountBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fixedDiscountField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(discountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(VIPGoldStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(discountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(discountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(discountsTabLayout.createSequentialGroup()
                                            .addComponent(VIPSilverStatusLbl)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(VIPSilverStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(VIPGoldStatusLbl))
                                    .addGroup(discountsTabLayout.createSequentialGroup()
                                        .addComponent(VIPDiamondStatusLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(VIPDiamondStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(2, 2, 2)))
                .addGap(0, 80, Short.MAX_VALUE))
        );
        discountsTabLayout.setVerticalGroup(
            discountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discountsTabLayout.createSequentialGroup()
                .addComponent(vipCustomerScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(discountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fixedDiscountBtn)
                    .addComponent(fixedDiscountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(discountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flexibleDiscountBtn)
                    .addComponent(flexibleDiscountBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setDiscountBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(discountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VIPSilverStatusLbl)
                    .addComponent(VIPSilverStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(discountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VIPGoldStatusLbl)
                    .addComponent(VIPGoldStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(discountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VIPDiamondStatusLbl)
                    .addComponent(VIPDiamondStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        managerTabs.addTab("Discounts", discountsTab);

        accountsSelectLbl.setText("Select account");

        accountsSelectBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Employee account 1", "Employee account 2", "Employee account 3", "Employee account 4", "Employee account 5", "Employee account 6" }));

        nameLbl.setText("Name");

        surnameLbl.setText("Surname");

        emailLbl.setText("E-mail");

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        accountTypeLbl.setText("Type");

        accountTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Staff", "Manager" }));

        accountAddBtn.setText("Add account");

        accountUpdateBtn.setText("Update account");

        accountDeleteBtn.setText("Delete account");
        accountDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountDeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountsTabLayout = new javax.swing.GroupLayout(accountsTab);
        accountsTab.setLayout(accountsTabLayout);
        accountsTabLayout.setHorizontalGroup(
            accountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountsTabLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(accountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountsTabLayout.createSequentialGroup()
                        .addComponent(accountAddBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountUpdateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountDeleteBtn))
                    .addGroup(accountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(accountsTabLayout.createSequentialGroup()
                            .addGroup(accountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(surnameLbl)
                                .addComponent(nameLbl)
                                .addComponent(emailLbl)
                                .addComponent(accountTypeLbl))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(accountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameField)
                                .addComponent(surnameField)
                                .addComponent(emailField)
                                .addComponent(accountTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(accountsTabLayout.createSequentialGroup()
                            .addComponent(accountsSelectLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(accountsSelectBox, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        accountsTabLayout.setVerticalGroup(
            accountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountsTabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(accountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountsSelectLbl)
                    .addComponent(accountsSelectBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(accountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surnameLbl)
                    .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountTypeLbl)
                    .addComponent(accountTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(accountsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountAddBtn)
                    .addComponent(accountDeleteBtn)
                    .addComponent(accountUpdateBtn))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        managerTabs.addTab("Accounts", accountsTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(managerTabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managerTabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("Manager Window");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportTypeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportTypeBoxActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        reportType = (String)cb.getSelectedItem();
    }//GEN-LAST:event_reportTypeBoxActionPerformed

    private void reportFromFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportFromFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportFromFieldActionPerformed

    private void fixedDiscountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixedDiscountBtnActionPerformed
        fixedDiscountField.setEnabled(true);
        flexibleDiscountBox.setEnabled(false);
    }//GEN-LAST:event_fixedDiscountBtnActionPerformed

    private void flexibleDiscountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flexibleDiscountBtnActionPerformed
        flexibleDiscountBox.setEnabled(true);
        fixedDiscountField.setEnabled(false);
        setDiscountBtn.setEnabled(true);
    }//GEN-LAST:event_flexibleDiscountBtnActionPerformed

    private void fixedDiscountFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fixedDiscountFieldKeyTyped
        setDiscountBtn.setEnabled(true);
    }//GEN-LAST:event_fixedDiscountFieldKeyTyped

    private void vipCustomersListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vipCustomersListMouseClicked
        fixedDiscountBtn.setEnabled(true);
        flexibleDiscountBtn.setEnabled(true);
    }//GEN-LAST:event_vipCustomersListMouseClicked

    private void productsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsListMouseClicked
        quantityField.setEnabled(true);
    }//GEN-LAST:event_productsListMouseClicked

    private void quantityFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityFieldKeyPressed
        updateStockBtn.setEnabled(true);
    }//GEN-LAST:event_quantityFieldKeyPressed

    private void reportGenerateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportGenerateBtnActionPerformed
        ((CardLayout)reportsPanel.getLayout()).show(reportsPanel, reportType);
        reportFrame.setTitle(reportType);
        reportFrame.setVisible(true);
    }//GEN-LAST:event_reportGenerateBtnActionPerformed

    private void deleteItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemBtnActionPerformed
        JOptionPane.showConfirmDialog(null, "<html>Are you sure you want to delete this item?<br>The action is irreversible.",
                "Deletion confirmation", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_deleteItemBtnActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void accountDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountDeleteBtnActionPerformed
        JOptionPane.showConfirmDialog(null, "<html>Are you sure you want to delete this account?<br>The action is irreversible.",
                "Deletion confirmation", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_accountDeleteBtnActionPerformed

    private void refundRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refundRecordBtnActionPerformed
        JOptionPane.showMessageDialog(null, "Refund successfully recorded.", "Refund recorded", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_refundRecordBtnActionPerformed

    private void isAvailableBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isAvailableBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isAvailableBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerWindow(conn, user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField VIPDiamondStatusField;
    private javax.swing.JLabel VIPDiamondStatusLbl;
    private javax.swing.JTextField VIPGoldStatusField;
    private javax.swing.JLabel VIPGoldStatusLbl;
    private javax.swing.JTextField VIPSilverStatusField;
    private javax.swing.JLabel VIPSilverStatusLbl;
    private javax.swing.JButton accountAddBtn;
    private javax.swing.JButton accountDeleteBtn;
    private javax.swing.JComboBox accountTypeBox;
    private javax.swing.JLabel accountTypeLbl;
    private javax.swing.JButton accountUpdateBtn;
    private javax.swing.JComboBox accountsSelectBox;
    private javax.swing.JLabel accountsSelectLbl;
    private javax.swing.JPanel accountsTab;
    private javax.swing.JButton addItemBtn;
    private javax.swing.JScrollPane customerSpendingReportSP;
    private javax.swing.JTable customerSpendingReportTable;
    private javax.swing.JScrollPane customersLoggedInReportSP;
    private javax.swing.JComboBox dailySpecialBox;
    private javax.swing.JLabel dailySpecialLbl;
    private javax.swing.JButton deleteItemBtn;
    private javax.swing.ButtonGroup discountSelector;
    private javax.swing.JPanel discountsTab;
    private javax.swing.JTextArea editDescriptionArea;
    private javax.swing.JLabel editDescriptionLbl;
    private javax.swing.JScrollPane editDescriptionScroll;
    private javax.swing.JTextField editDurationField;
    private javax.swing.JLabel editDurationLbl;
    private javax.swing.JTextField editNameField;
    private javax.swing.JLabel editNameLbl;
    private javax.swing.JTextField editPriceField;
    private javax.swing.JLabel editPriceLbl;
    private javax.swing.JComboBox editTypeBox;
    private javax.swing.JLabel editTypeLbl;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JRadioButton fixedDiscountBtn;
    private javax.swing.JTextField fixedDiscountField;
    private javax.swing.JComboBox flexibleDiscountBox;
    private javax.swing.JRadioButton flexibleDiscountBtn;
    private javax.swing.JCheckBox isAvailableBox;
    private javax.swing.JPanel manageMenuTab;
    private javax.swing.JTabbedPane managerTabs;
    private javax.swing.JList menuItemsList;
    private javax.swing.JScrollPane menuItemsScroll;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JScrollPane ordersReportSP;
    private javax.swing.JTable ordersReportTable;
    private javax.swing.JList productsList;
    private javax.swing.JScrollPane productsScroll;
    private javax.swing.JTextField quantityField;
    private javax.swing.JLabel quantityLbl;
    private javax.swing.JTextField refundPaymentIDField;
    private javax.swing.JLabel refundPaymentIDLbl;
    private javax.swing.JButton refundRecordBtn;
    private javax.swing.JScrollPane refundReportSP;
    private javax.swing.JTable refundReportTable;
    private javax.swing.JLabel refundTitleLbl;
    private javax.swing.JFrame reportFrame;
    private javax.swing.JTextField reportFromField;
    private javax.swing.JLabel reportFromLbl;
    private javax.swing.JButton reportGenerateBtn;
    private javax.swing.JButton reportPrintBtn;
    private javax.swing.JTextField reportSearchField;
    private javax.swing.JLabel reportSearchLbl;
    private javax.swing.JTextField reportToField;
    private javax.swing.JLabel reportToLbl;
    private javax.swing.JComboBox reportTypeBox;
    private javax.swing.JLabel reportTypeLbl;
    private javax.swing.JSeparator reportsAndRefundsSeparator;
    private javax.swing.JPanel reportsAndRefundsTab;
    private javax.swing.JPanel reportsPanel;
    private javax.swing.JButton setDiscountBtn;
    private javax.swing.JScrollPane staffPerformanceReportSP;
    private javax.swing.JTable staffPerformanceReportTable;
    private javax.swing.JTextField surnameField;
    private javax.swing.JLabel surnameLbl;
    private javax.swing.JButton updateItemBtn;
    private javax.swing.JButton updateStockBtn;
    private javax.swing.JPanel updateStockTab;
    private javax.swing.JTable usersLoggedInReportTable;
    private javax.swing.JScrollPane vipCustomerScroll;
    private javax.swing.JList vipCustomersList;
    // End of variables declaration//GEN-END:variables
}
