/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CoD.gui;

import CoD.User;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Stefan
 */
public class NoLoginMenu extends javax.swing.JFrame {
    
    private static CoD.DBConnect    conn;
    private CoD.User                user;

    /**
     * Creates new form NoLoginMenu
     * @param conn
     */
    public NoLoginMenu(CoD.DBConnect conn) {
        initComponents();
        this.conn = conn;
        registerNameField.setInputVerifier(new CoD.NameValidator(
                registerDialog,
                registerNameField));
        registerSurnameField.setInputVerifier(new CoD.NameValidator(
                registerDialog,
                registerSurnameField));
        registerEmailField.setInputVerifier(new CoD.EmailValidator(
                registerDialog,
                registerEmailField));
        registerPassField.setInputVerifier(new CoD.PasswordValidator(
                registerDialog,
                registerPassField,
                registerPassField));
        registerRepeatPassField.setInputVerifier(new CoD.PasswordValidator(
                registerDialog,
                registerPassField,
                registerRepeatPassField));
        registerMobileNoField.setInputVerifier(new CoD.MobileNoValidator(
                registerDialog,
                registerMobileNoField));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginDialog = new javax.swing.JDialog();
        loginEmailLbl = new javax.swing.JLabel();
        loginEmailField = new javax.swing.JTextField();
        loginPassLbl = new javax.swing.JLabel();
        loginPassField = new javax.swing.JPasswordField();
        dialogLoginBtn = new javax.swing.JButton();
        dialogRegisterBtn = new javax.swing.JButton();
        wrongLoginLbl = new javax.swing.JLabel();
        wrongLoginLbl.setVisible(false);
        menuSelectGroup = new javax.swing.ButtonGroup();
        registerDialog = new javax.swing.JDialog();
        registerNameLbl = new javax.swing.JLabel();
        registerNameField = new javax.swing.JTextField();
        registerSurnameLbl = new javax.swing.JLabel();
        registerSurnameField = new javax.swing.JTextField();
        registerEmailLbl = new javax.swing.JLabel();
        registerEmailField = new javax.swing.JTextField();
        registerPassLbl = new javax.swing.JLabel();
        registerPassField = new javax.swing.JPasswordField();
        registerRepeatPassLbl = new javax.swing.JLabel();
        registerRepeatPassField = new javax.swing.JPasswordField();
        registerMoblieNoLbl = new javax.swing.JLabel();
        registerMobileNoField = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        welcomeTitleLbl = new javax.swing.JLabel();
        welcomeTextLbl = new javax.swing.JLabel();
        frameLoginBtn = new javax.swing.JButton();
        frameRegisterBtn = new javax.swing.JButton();
        menuTab = new javax.swing.JPanel();
        breakfastSelect = new javax.swing.JRadioButton();
        lunchSelect = new javax.swing.JRadioButton();
        dinnerSelect = new javax.swing.JRadioButton();
        drinksSelect = new javax.swing.JRadioButton();
        orderTotalCostLbl = new javax.swing.JLabel();
        orderTotalCostField = new javax.swing.JTextField();
        orderBtn = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        breakfastMenuSP = new javax.swing.JScrollPane();
        breakfastMenuPanel = new javax.swing.JPanel();
        PN1 = new javax.swing.JCheckBox();
        PD1 = new javax.swing.JLabel();
        PP1 = new javax.swing.JLabel();
        PN2 = new javax.swing.JCheckBox();
        PD2 = new javax.swing.JLabel();
        PP2 = new javax.swing.JLabel();
        PN3 = new javax.swing.JCheckBox();
        PD3 = new javax.swing.JLabel();
        PP3 = new javax.swing.JLabel();
        PN4 = new javax.swing.JCheckBox();
        PD4 = new javax.swing.JLabel();
        PP4 = new javax.swing.JLabel();
        PN5 = new javax.swing.JCheckBox();
        PD5 = new javax.swing.JLabel();
        PP5 = new javax.swing.JLabel();
        PN6 = new javax.swing.JCheckBox();
        PD6 = new javax.swing.JLabel();
        PP6 = new javax.swing.JLabel();
        PN7 = new javax.swing.JCheckBox();
        PD7 = new javax.swing.JLabel();
        PP7 = new javax.swing.JLabel();
        PN8 = new javax.swing.JCheckBox();
        PD8 = new javax.swing.JLabel();
        PP8 = new javax.swing.JLabel();
        basketSP = new javax.swing.JScrollPane();
        basketTable = new javax.swing.JTable();
        basketLbl = new javax.swing.JLabel();

        loginDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        loginDialog.setTitle("Login");
        loginDialog.setAlwaysOnTop(true);
        loginDialog.setLocationByPlatform(true);
        loginDialog.setMinimumSize(new java.awt.Dimension(250, 165));
        loginDialog.setResizable(false);

        loginEmailLbl.setText("Email");

        loginPassLbl.setText("Password");

        dialogLoginBtn.setText("Login");
        dialogLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogLoginBtnActionPerformed(evt);
            }
        });

        dialogRegisterBtn.setText("Register");
        dialogRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogRegisterBtnActionPerformed(evt);
            }
        });

        wrongLoginLbl.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        wrongLoginLbl.setForeground(new java.awt.Color(255, 0, 0));
        wrongLoginLbl.setText("Wrong email and/or password.");
        wrongLoginLbl.setFocusable(false);

        javax.swing.GroupLayout loginDialogLayout = new javax.swing.GroupLayout(loginDialog.getContentPane());
        loginDialog.getContentPane().setLayout(loginDialogLayout);
        loginDialogLayout.setHorizontalGroup(
            loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginPassLbl)
                    .addComponent(loginEmailLbl))
                .addGap(18, 18, 18)
                .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginEmailField)
                    .addComponent(loginPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(loginDialogLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wrongLoginLbl)
                    .addGroup(loginDialogLayout.createSequentialGroup()
                        .addComponent(dialogLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dialogRegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginDialogLayout.setVerticalGroup(
            loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginEmailLbl)
                    .addComponent(loginEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginPassLbl)
                    .addComponent(loginPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wrongLoginLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialogLoginBtn)
                    .addComponent(dialogRegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        registerDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        registerDialog.setTitle("Register");
        registerDialog.setAlwaysOnTop(true);
        registerDialog.setLocationByPlatform(true);
        registerDialog.setMinimumSize(new java.awt.Dimension(280, 350));
        registerDialog.setResizable(false);

        registerNameLbl.setText("Name");

        registerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerNameFieldActionPerformed(evt);
            }
        });

        registerSurnameLbl.setText("Surname");

        registerEmailLbl.setText("E-mail");

        registerEmailField.setText("example@domain.com");
        registerEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerEmailFieldActionPerformed(evt);
            }
        });

        registerPassLbl.setText("Password");

        registerPassField.setName("pass"); // NOI18N
        registerPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPassFieldActionPerformed(evt);
            }
        });

        registerRepeatPassLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerRepeatPassLbl.setText("<html>Repeat<br>Password");
        registerRepeatPassLbl.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        registerRepeatPassField.setName("repeatPass"); // NOI18N

        registerMoblieNoLbl.setText("<html>Mobile number<br>(optional)");
        registerMoblieNoLbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        registerMobileNoField.setMaximumSize(new java.awt.Dimension(170, 2147483647));
        registerMobileNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerMobileNoFieldActionPerformed(evt);
            }
        });

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerDialogLayout = new javax.swing.GroupLayout(registerDialog.getContentPane());
        registerDialog.getContentPane().setLayout(registerDialogLayout);
        registerDialogLayout.setHorizontalGroup(
            registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerDialogLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registerMoblieNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerEmailLbl)
                    .addComponent(registerSurnameLbl)
                    .addComponent(registerNameLbl)
                    .addComponent(registerPassLbl)
                    .addComponent(registerRepeatPassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerBtn)
                    .addGroup(registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(registerRepeatPassField)
                        .addComponent(registerPassField)
                        .addComponent(registerSurnameField)
                        .addComponent(registerEmailField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(registerNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(registerMobileNoField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        registerDialogLayout.setVerticalGroup(
            registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerNameLbl)
                    .addComponent(registerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerSurnameLbl)
                    .addComponent(registerSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerEmailLbl))
                .addGap(18, 18, 18)
                .addGroup(registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerPassLbl))
                .addGap(18, 18, 18)
                .addGroup(registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerRepeatPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerRepeatPassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(registerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerMobileNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerMoblieNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registerBtn)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        registerMobileNoField.setText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chich Cafe - you are not logged in");
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(610, 577));
        setPreferredSize(new java.awt.Dimension(610, 507));

        welcomeTitleLbl.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        welcomeTitleLbl.setText("Welcome to Chick Cafe");

        welcomeTextLbl.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        welcomeTextLbl.setText("<html>In order to use this app, you have to log in or register with your email and<br>password. Once you do, all the functionality will be available to you.");

        frameLoginBtn.setText("Log in");
        frameLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameLoginBtnActionPerformed(evt);
            }
        });

        frameRegisterBtn.setText("Register");
        frameRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameRegisterBtnActionPerformed(evt);
            }
        });

        menuTab.setPreferredSize(new java.awt.Dimension(570, 500));

        menuSelectGroup.add(breakfastSelect);
        breakfastSelect.setSelected(true);
        breakfastSelect.setText("Breakfast");

        menuSelectGroup.add(lunchSelect);
        lunchSelect.setText("Lunch");

        menuSelectGroup.add(dinnerSelect);
        dinnerSelect.setText("Dinner");

        menuSelectGroup.add(drinksSelect);
        drinksSelect.setText("Drinks");

        orderTotalCostLbl.setText("Total cost");
        orderTotalCostLbl.setEnabled(false);

        orderTotalCostField.setEditable(false);
        orderTotalCostField.setColumns(3);
        orderTotalCostField.setText("0");
        orderTotalCostField.setEnabled(false);
        orderTotalCostField.setFocusable(false);
        orderTotalCostField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderTotalCostFieldActionPerformed(evt);
            }
        });

        orderBtn.setText("Place Order");
        orderBtn.setDoubleBuffered(true);
        orderBtn.setEnabled(false);
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnActionPerformed(evt);
            }
        });

        menuPanel.setEnabled(false);
        menuPanel.setPreferredSize(new java.awt.Dimension(301, 365));
        menuPanel.setLayout(new java.awt.CardLayout());

        breakfastMenuSP.setPreferredSize(new java.awt.Dimension(600, 100));

        breakfastMenuPanel.setPreferredSize(new java.awt.Dimension(274, 604));

        PN1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PN1.setText("Product Name");
        PN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PN1ActionPerformed(evt);
            }
        });

        PD1.setText("<Product description>");
        PD1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PD1.setMaximumSize(new java.awt.Dimension(110, 15));
        PD1.setMinimumSize(new java.awt.Dimension(110, 15));
        PD1.setPreferredSize(new java.awt.Dimension(110, 15));

        PP1.setText("12");

        PN2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PN2.setText("Product Name");
        PN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PN2ActionPerformed(evt);
            }
        });

        PD2.setText("<Product description>");
        PD2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PD2.setMaximumSize(new java.awt.Dimension(110, 15));
        PD2.setMinimumSize(new java.awt.Dimension(110, 15));
        PD2.setPreferredSize(new java.awt.Dimension(110, 15));

        PP2.setText("Price");

        PN3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PN3.setText("Product Name");

        PD3.setText("<Product description>");
        PD3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PD3.setMaximumSize(new java.awt.Dimension(110, 15));
        PD3.setMinimumSize(new java.awt.Dimension(110, 15));
        PD3.setPreferredSize(new java.awt.Dimension(110, 15));

        PP3.setText("Price");

        PN4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PN4.setText("Product Name");

        PD4.setText("<Product description>");
        PD4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PD4.setMaximumSize(new java.awt.Dimension(110, 15));
        PD4.setMinimumSize(new java.awt.Dimension(110, 15));
        PD4.setPreferredSize(new java.awt.Dimension(110, 15));

        PP4.setText("Price");

        PN5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PN5.setText("Product Name");

        PD5.setText("<Product description>");
        PD5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PD5.setMaximumSize(new java.awt.Dimension(110, 15));
        PD5.setMinimumSize(new java.awt.Dimension(110, 15));
        PD5.setPreferredSize(new java.awt.Dimension(110, 15));

        PP5.setText("Price");

        PN6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PN6.setText("Product Name");

        PD6.setText("<Product description>");
        PD6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PD6.setMaximumSize(new java.awt.Dimension(110, 15));
        PD6.setMinimumSize(new java.awt.Dimension(110, 15));
        PD6.setPreferredSize(new java.awt.Dimension(110, 15));

        PP6.setText("Price");

        PN7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PN7.setText("Product Name");

        PD7.setText("<Product description>");
        PD7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PD7.setMaximumSize(new java.awt.Dimension(110, 15));
        PD7.setMinimumSize(new java.awt.Dimension(110, 15));
        PD7.setPreferredSize(new java.awt.Dimension(110, 15));

        PP7.setText("Price");

        PN8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PN8.setText("Product Name");

        PD8.setText("<Product description>");
        PD8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PD8.setMaximumSize(new java.awt.Dimension(110, 15));
        PD8.setMinimumSize(new java.awt.Dimension(110, 15));
        PD8.setPreferredSize(new java.awt.Dimension(110, 15));

        PP8.setText("Price");

        javax.swing.GroupLayout breakfastMenuPanelLayout = new javax.swing.GroupLayout(breakfastMenuPanel);
        breakfastMenuPanel.setLayout(breakfastMenuPanelLayout);
        breakfastMenuPanelLayout.setHorizontalGroup(
            breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(breakfastMenuPanelLayout.createSequentialGroup()
                .addGroup(breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(breakfastMenuPanelLayout.createSequentialGroup()
                            .addComponent(PN7)
                            .addGap(102, 102, 102)
                            .addComponent(PP7))
                        .addComponent(PD7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(breakfastMenuPanelLayout.createSequentialGroup()
                            .addComponent(PN6)
                            .addGap(102, 102, 102)
                            .addComponent(PP6))
                        .addComponent(PD6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(breakfastMenuPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(PD8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, breakfastMenuPanelLayout.createSequentialGroup()
                                .addComponent(PN8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PP8))))
                    .addGroup(breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(breakfastMenuPanelLayout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(PD5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(breakfastMenuPanelLayout.createSequentialGroup()
                                    .addComponent(PN5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PP5)))
                            .addGroup(breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(breakfastMenuPanelLayout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(PD4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(breakfastMenuPanelLayout.createSequentialGroup()
                                    .addComponent(PN4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PP4))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, breakfastMenuPanelLayout.createSequentialGroup()
                                .addComponent(PN2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PP2))
                            .addGroup(breakfastMenuPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(PD2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(breakfastMenuPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(PD3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, breakfastMenuPanelLayout.createSequentialGroup()
                                .addComponent(PN3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PP3)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(breakfastMenuPanelLayout.createSequentialGroup()
                                .addComponent(PN1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PP1))
                            .addGroup(breakfastMenuPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(PD1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        breakfastMenuPanelLayout.setVerticalGroup(
            breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(breakfastMenuPanelLayout.createSequentialGroup()
                .addGroup(breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PN1)
                    .addComponent(PP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PD1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PN2)
                    .addComponent(PP2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PD2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PN3)
                    .addComponent(PP3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PD3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PN4)
                    .addComponent(PP4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PD4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PN5)
                    .addComponent(PP5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PD5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PN6)
                    .addComponent(PP6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PD6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(breakfastMenuPanelLayout.createSequentialGroup()
                        .addComponent(PP7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PD7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PN7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(breakfastMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PN8)
                    .addComponent(PP8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PD8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        breakfastMenuSP.setViewportView(breakfastMenuPanel);

        menuPanel.add(breakfastMenuSP, "card2");

        basketSP.setEnabled(false);

        basketTable.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        basketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Product", "Qty.", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        basketTable.setFillsViewportHeight(true);
        basketTable.setMaximumSize(new java.awt.Dimension(500, 1000));
        basketTable.setMinimumSize(new java.awt.Dimension(225, 350));
        basketTable.setPreferredSize(new java.awt.Dimension(225, 350));
        basketTable.setRowHeight(20);
        basketTable.setShowHorizontalLines(true);
        basketSP.setViewportView(basketTable);
        basketTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (basketTable.getColumnModel().getColumnCount() > 0) {
            basketTable.getColumnModel().getColumn(0).setResizable(false);
            basketTable.getColumnModel().getColumn(1).setResizable(false);
            basketTable.getColumnModel().getColumn(2).setResizable(false);
        }

        basketLbl.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        basketLbl.setText("Basket");

        javax.swing.GroupLayout menuTabLayout = new javax.swing.GroupLayout(menuTab);
        menuTab.setLayout(menuTabLayout);
        menuTabLayout.setHorizontalGroup(
            menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuTabLayout.createSequentialGroup()
                .addGroup(menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(menuTabLayout.createSequentialGroup()
                        .addComponent(breakfastSelect)
                        .addGap(18, 18, 18)
                        .addComponent(lunchSelect)
                        .addGap(18, 18, 18)
                        .addComponent(dinnerSelect)
                        .addGap(18, 18, 18)
                        .addComponent(drinksSelect))
                    .addGroup(menuTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGroup(menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuTabLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(basketSP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(menuTabLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(basketLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(125, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuTabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(orderTotalCostLbl)
                .addGap(0, 0, 0)
                .addComponent(orderTotalCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orderBtn)
                .addGap(26, 26, 26))
        );
        menuTabLayout.setVerticalGroup(
            menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breakfastSelect)
                    .addComponent(lunchSelect)
                    .addComponent(dinnerSelect)
                    .addComponent(drinksSelect)
                    .addComponent(basketLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(basketSP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderBtn)
                    .addComponent(orderTotalCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderTotalCostLbl))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menuTab, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeTitleLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(welcomeTextLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(frameLoginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(frameRegisterBtn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frameLoginBtn)
                    .addComponent(welcomeTitleLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(welcomeTextLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frameRegisterBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuTab, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Chick Cafe no login");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frameLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameLoginBtnActionPerformed
        loginDialog.setVisible(true);
    }//GEN-LAST:event_frameLoginBtnActionPerformed

    private void dialogRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogRegisterBtnActionPerformed
        if(loginDialog.isVisible()) loginDialog.setVisible(false);
        registerDialog.setVisible(true);
    }//GEN-LAST:event_dialogRegisterBtnActionPerformed

    private void dialogLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogLoginBtnActionPerformed
        user = new CoD.User(
                loginEmailField.getText(),
                loginPassField.getText(),
                conn);
        if(user.login())
        {
            String type = user.getType();
            switch (type)
            {
                case "Customer" : 
                {
                    new ClientWindow(conn, user).main(new String[0]);
                    loginDialog.dispose();
                    this.dispose();
                    break;
                }
                case "Staff" :
                {
                    new StaffWindow(conn, user).main(new String[0]);
                    loginDialog.dispose();
                    this.dispose();
                    break;
                }
                case "Manager" :
                {
                    new ManagerWindow(conn, user).main(new String[0]);
                    loginDialog.dispose();
                    this.dispose();
                    break;
                }
                case "Owner" :
                {
                    new StaffWindow(conn, user).main(new String[0]);
                    new ManagerWindow(conn, user).main(new String[0]);
                    new OwnerWindow(conn).main(new String [0]);
                    loginDialog.dispose();
                    this.dispose();
                    break;
                }
                default : 
                {
                    loginDialog.dispose();
                    this.dispose();
                }
            }    
        }
        else
            wrongLoginLbl.setVisible(true);
    }//GEN-LAST:event_dialogLoginBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        String mobileNo = "";
        if (!registerMobileNoField.getText().isEmpty())
            mobileNo = registerMobileNoField.getText();
        
        int userID;
        userID = conn.register(
                "Customer",
                registerNameField.getText(),
                registerSurnameField.getText(),
                registerEmailField.getText(),
                User.encryptPassword(registerPassField.getText().getBytes()),
                mobileNo);
        
        if (userID != -1)
            javax.swing.JOptionPane.showMessageDialog(
                registerDialog,
                "<html>Your account has been successfully created.<br>"
                    + "You can now log in with your account.",
                "Registration complete",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        else javax.swing.JOptionPane.showMessageDialog(
                registerDialog,
                "<html>Your registration did not complete successfully.<br>"
                    + "Please try again.",
                "Registration unsuccessful",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_registerBtnActionPerformed

    private void registerEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerEmailFieldActionPerformed

    }//GEN-LAST:event_registerEmailFieldActionPerformed

    private void frameRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameRegisterBtnActionPerformed
        registerDialog.setVisible(true);
    }//GEN-LAST:event_frameRegisterBtnActionPerformed

    private void registerMobileNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerMobileNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerMobileNoFieldActionPerformed

    private void registerPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerPassFieldActionPerformed

    private void orderTotalCostFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderTotalCostFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderTotalCostFieldActionPerformed

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
        
    }//GEN-LAST:event_orderBtnActionPerformed

    private void PN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PN1ActionPerformed
        
    }//GEN-LAST:event_PN1ActionPerformed

    private void PN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PN2ActionPerformed
       
    }//GEN-LAST:event_PN2ActionPerformed

    private void registerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoLoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoLoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoLoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoLoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NoLoginMenu(conn).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PD1;
    private javax.swing.JLabel PD2;
    private javax.swing.JLabel PD3;
    private javax.swing.JLabel PD4;
    private javax.swing.JLabel PD5;
    private javax.swing.JLabel PD6;
    private javax.swing.JLabel PD7;
    private javax.swing.JLabel PD8;
    private javax.swing.JCheckBox PN1;
    private javax.swing.JCheckBox PN2;
    private javax.swing.JCheckBox PN3;
    private javax.swing.JCheckBox PN4;
    private javax.swing.JCheckBox PN5;
    private javax.swing.JCheckBox PN6;
    private javax.swing.JCheckBox PN7;
    private javax.swing.JCheckBox PN8;
    private javax.swing.JLabel PP1;
    private javax.swing.JLabel PP2;
    private javax.swing.JLabel PP3;
    private javax.swing.JLabel PP4;
    private javax.swing.JLabel PP5;
    private javax.swing.JLabel PP6;
    private javax.swing.JLabel PP7;
    private javax.swing.JLabel PP8;
    private javax.swing.JLabel basketLbl;
    private javax.swing.JScrollPane basketSP;
    private javax.swing.JTable basketTable;
    private javax.swing.JPanel breakfastMenuPanel;
    private javax.swing.JScrollPane breakfastMenuSP;
    private javax.swing.JRadioButton breakfastSelect;
    private javax.swing.JButton dialogLoginBtn;
    private javax.swing.JButton dialogRegisterBtn;
    private javax.swing.JRadioButton dinnerSelect;
    private javax.swing.JRadioButton drinksSelect;
    private javax.swing.JButton frameLoginBtn;
    private javax.swing.JButton frameRegisterBtn;
    private javax.swing.JDialog loginDialog;
    private javax.swing.JTextField loginEmailField;
    private javax.swing.JLabel loginEmailLbl;
    private javax.swing.JPasswordField loginPassField;
    private javax.swing.JLabel loginPassLbl;
    private javax.swing.JRadioButton lunchSelect;
    private javax.swing.JPanel menuPanel;
    private javax.swing.ButtonGroup menuSelectGroup;
    private javax.swing.JPanel menuTab;
    private javax.swing.JButton orderBtn;
    private javax.swing.JTextField orderTotalCostField;
    private javax.swing.JLabel orderTotalCostLbl;
    private javax.swing.JButton registerBtn;
    private javax.swing.JDialog registerDialog;
    private javax.swing.JTextField registerEmailField;
    private javax.swing.JLabel registerEmailLbl;
    private javax.swing.JTextField registerMobileNoField;
    private javax.swing.JLabel registerMoblieNoLbl;
    private javax.swing.JTextField registerNameField;
    private javax.swing.JLabel registerNameLbl;
    private javax.swing.JPasswordField registerPassField;
    private javax.swing.JLabel registerPassLbl;
    private javax.swing.JPasswordField registerRepeatPassField;
    private javax.swing.JLabel registerRepeatPassLbl;
    private javax.swing.JTextField registerSurnameField;
    private javax.swing.JLabel registerSurnameLbl;
    private javax.swing.JLabel welcomeTextLbl;
    private javax.swing.JLabel welcomeTitleLbl;
    private javax.swing.JLabel wrongLoginLbl;
    // End of variables declaration//GEN-END:variables
}
