/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CoD.gui;

/**
 *
 * @author Stefan
 */
public class StaffWindow extends javax.swing.JFrame {
    private static CoD.DBConnect    conn;
    private static CoD.User         user;

    /**
     * Creates new form StaffWindow1
     * @param conn
     * @param user
     */
    public StaffWindow(CoD.DBConnect conn, CoD.User user) {
        initComponents();
        this.conn = conn;
        this.user = user;
        accountNewEmailField.setInputVerifier(new CoD.EmailValidator(
                accountNewEmailField.getParent(),
                accountNewEmailField));
        accountNewPassField.setInputVerifier(new CoD.PasswordValidator(
                accountNewPassField.getParent(),
                accountNewPassField,
                accountNewPassField));
        accountNewPass2Field.setInputVerifier(new CoD.PasswordValidator(
                accountNewPass2Field.getParent(),
                accountNewPassField,
                accountNewPass2Field));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountManagerSelector = new javax.swing.ButtonGroup();
        staffTabs = new javax.swing.JTabbedPane();
        ordersTab = new javax.swing.JPanel();
        ordersPendingLbl = new javax.swing.JLabel();
        ordersScrollPane = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        ordersSelectedLbl = new javax.swing.JLabel();
        orderContentsScroll = new javax.swing.JScrollPane();
        orderContentsList = new javax.swing.JList();
        orderProcessBtn = new javax.swing.JButton();
        orderCompleteBtn = new javax.swing.JButton();
        orderPrintPendingBtn = new javax.swing.JButton();
        accountTab = new javax.swing.JPanel();
        accountChangePassBtn = new javax.swing.JButton();
        accountNewPassField = new javax.swing.JPasswordField();
        accountNewPass2Lbl = new javax.swing.JLabel();
        accountPassLbl = new javax.swing.JLabel();
        accountChangeEmailBtn = new javax.swing.JButton();
        accountPassField = new javax.swing.JPasswordField();
        accountNewEmailField = new javax.swing.JTextField();
        accountNewPassLbl = new javax.swing.JLabel();
        accountNewEmailLbl = new javax.swing.JLabel();
        accountOldPassField = new javax.swing.JPasswordField();
        accountNewPass2Field = new javax.swing.JPasswordField();
        accountOldPassLbl = new javax.swing.JLabel();
        accountChangePassSelect = new javax.swing.JRadioButton();
        accountChangeEmailSelect = new javax.swing.JRadioButton();
        separator = new javax.swing.JSeparator();
        accountPerformanceLbl = new javax.swing.JLabel();
        accountPerformanceSP = new javax.swing.JScrollPane();
        accountPerformanceTable = new javax.swing.JTable();
        accountOrderCountLbl = new javax.swing.JLabel();
        accountOrderCountField = new javax.swing.JTextField();
        accountPrintReportBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CoD Staff");

        ordersPendingLbl.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ordersPendingLbl.setText("Pending orders");

        ordersTable.setAutoCreateRowSorter(true);
        ordersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Breakfast", "10:23:00",  new Integer(15), "John Snow", "john@gmail.com", "07856429512",  new Boolean(true)},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order type", "Time placed", "Intended duration", "Customer name", "Customer email", "Mobile No.", "Priority"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ordersTable.setColumnSelectionAllowed(true);
        ordersTable.setMinimumSize(new java.awt.Dimension(535, 160));
        ordersTable.setPreferredSize(new java.awt.Dimension(535, 160));
        ordersTable.setSelectionBackground(new java.awt.Color(0, 153, 153));
        ordersTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ordersTable.setShowHorizontalLines(true);
        ordersTable.setShowVerticalLines(true);
        ordersScrollPane.setViewportView(ordersTable);
        ordersTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        ordersSelectedLbl.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        ordersSelectedLbl.setText("Selected order contents");

        orderContentsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        orderContentsScroll.setViewportView(orderContentsList);

        orderProcessBtn.setText("Process order");

        orderCompleteBtn.setText("Complete order");
        orderCompleteBtn.setToolTipText("Sends a notification to the customer that the order is ready for pickup.");

        orderPrintPendingBtn.setText("Print pending orders");

        javax.swing.GroupLayout ordersTabLayout = new javax.swing.GroupLayout(ordersTab);
        ordersTab.setLayout(ordersTabLayout);
        ordersTabLayout.setHorizontalGroup(
            ordersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersTabLayout.createSequentialGroup()
                .addGroup(ordersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ordersTabLayout.createSequentialGroup()
                        .addGroup(ordersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ordersTabLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(ordersPendingLbl))
                            .addGroup(ordersTabLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(orderContentsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(ordersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(orderCompleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orderProcessBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(orderPrintPendingBtn)))
                    .addGroup(ordersTabLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ordersSelectedLbl)))
                .addContainerGap(187, Short.MAX_VALUE))
            .addComponent(ordersScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        ordersTabLayout.setVerticalGroup(
            ordersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ordersPendingLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ordersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ordersSelectedLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ordersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderContentsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ordersTabLayout.createSequentialGroup()
                        .addComponent(orderProcessBtn)
                        .addGap(18, 18, 18)
                        .addComponent(orderCompleteBtn)
                        .addGap(18, 18, 18)
                        .addComponent(orderPrintPendingBtn)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        staffTabs.addTab("View orders", ordersTab);

        accountChangePassBtn.setText("Change Password");
        accountChangePassBtn.setEnabled(false);
        accountChangePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountChangePassBtnActionPerformed(evt);
            }
        });

        accountNewPassField.setEnabled(false);
        accountNewPassField.setName("accountNewPass"); // NOI18N

        accountNewPass2Lbl.setText("<html>Repreat new<br>password");
        accountNewPass2Lbl.setEnabled(false);

        accountPassLbl.setText("Password");
        accountPassLbl.setEnabled(false);

        accountChangeEmailBtn.setText("Change Email");
        accountChangeEmailBtn.setEnabled(false);
        accountChangeEmailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountChangeEmailBtnActionPerformed(evt);
            }
        });

        accountPassField.setEnabled(false);

        accountNewEmailField.setEnabled(false);

        accountNewPassLbl.setText("New password");
        accountNewPassLbl.setEnabled(false);

        accountNewEmailLbl.setText("New Email");
        accountNewEmailLbl.setEnabled(false);

        accountOldPassField.setEnabled(false);
        accountOldPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountOldPassFieldActionPerformed(evt);
            }
        });

        accountNewPass2Field.setEnabled(false);
        accountNewPass2Field.setName("repeatPass"); // NOI18N

        accountOldPassLbl.setText("Old password");
        accountOldPassLbl.setEnabled(false);

        accountManagerSelector.add(accountChangePassSelect);
        accountChangePassSelect.setText("Change Password");
        accountChangePassSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountChangePassSelectActionPerformed(evt);
            }
        });

        accountManagerSelector.add(accountChangeEmailSelect);
        accountChangeEmailSelect.setText("Change Email");
        accountChangeEmailSelect.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                accountChangeEmailSelectStateChanged(evt);
            }
        });
        accountChangeEmailSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountChangeEmailSelectActionPerformed(evt);
            }
        });

        accountPerformanceLbl.setText("Your performance information");

        accountPerformanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "OrderID", "Order type", "Order date", "Order time", "Preparation time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        accountPerformanceTable.setShowHorizontalLines(true);
        accountPerformanceTable.setShowVerticalLines(true);
        accountPerformanceSP.setViewportView(accountPerformanceTable);
        if (accountPerformanceTable.getColumnModel().getColumnCount() > 0) {
            accountPerformanceTable.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        accountOrderCountLbl.setText("Total orders prepared");

        accountOrderCountField.setColumns(4);

        accountPrintReportBtn.setText("Print");
        accountPrintReportBtn.setPreferredSize(new java.awt.Dimension(60, 28));

        javax.swing.GroupLayout accountTabLayout = new javax.swing.GroupLayout(accountTab);
        accountTab.setLayout(accountTabLayout);
        accountTabLayout.setHorizontalGroup(
            accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator)
            .addGroup(accountTabLayout.createSequentialGroup()
                .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountPerformanceSP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(accountTabLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(accountChangeEmailBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(accountTabLayout.createSequentialGroup()
                                    .addComponent(accountNewEmailLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(accountNewEmailField))
                                .addGroup(accountTabLayout.createSequentialGroup()
                                    .addComponent(accountPassLbl)
                                    .addGap(18, 18, 18)
                                    .addComponent(accountPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(accountChangeEmailSelect))
                        .addGap(72, 72, 72)
                        .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountChangePassSelect)
                            .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(accountTabLayout.createSequentialGroup()
                                    .addComponent(accountOldPassLbl)
                                    .addGap(18, 18, 18)
                                    .addComponent(accountOldPassField))
                                .addGroup(accountTabLayout.createSequentialGroup()
                                    .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(accountNewPassLbl)
                                        .addComponent(accountNewPass2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(accountNewPass2Field)
                                        .addComponent(accountNewPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(accountChangePassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(accountTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(accountTabLayout.createSequentialGroup()
                                .addComponent(accountPerformanceLbl)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(accountTabLayout.createSequentialGroup()
                                .addComponent(accountOrderCountLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(accountOrderCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                                .addComponent(accountPrintReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        accountTabLayout.setVerticalGroup(
            accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountTabLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountChangeEmailSelect)
                    .addComponent(accountChangePassSelect))
                .addGap(18, 18, 18)
                .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountOldPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountOldPassLbl)
                    .addComponent(accountNewEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountNewEmailLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNewPassLbl)
                    .addComponent(accountNewPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountPassLbl)
                    .addComponent(accountPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountNewPass2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountNewPass2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountChangePassBtn)
                    .addComponent(accountChangeEmailBtn))
                .addGap(18, 18, 18)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountPerformanceLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountPerformanceSP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountOrderCountLbl)
                    .addComponent(accountOrderCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountPrintReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        staffTabs.addTab("Manage account", accountTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staffTabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staffTabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountChangePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountChangePassBtnActionPerformed

    }//GEN-LAST:event_accountChangePassBtnActionPerformed

    private void accountChangeEmailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountChangeEmailBtnActionPerformed

    }//GEN-LAST:event_accountChangeEmailBtnActionPerformed

    private void accountOldPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountOldPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountOldPassFieldActionPerformed

    private void accountChangePassSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountChangePassSelectActionPerformed
        accountOldPassLbl.setEnabled(true);
        accountOldPassField.setEnabled(true);
        accountNewPassLbl.setEnabled(true);
        accountNewPassField.setEnabled(true);
        accountNewPass2Lbl.setEnabled(true);
        accountNewPass2Field.setEnabled(true);
        accountChangePassBtn.setEnabled(true);
        accountNewEmailLbl.setEnabled(false);
        accountNewEmailField.setEnabled(false);
        accountPassLbl.setEnabled(false);
        accountPassField.setEnabled(false);
        accountChangeEmailBtn.setEnabled(false);
    }//GEN-LAST:event_accountChangePassSelectActionPerformed

    private void accountChangeEmailSelectStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_accountChangeEmailSelectStateChanged

    }//GEN-LAST:event_accountChangeEmailSelectStateChanged

    private void accountChangeEmailSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountChangeEmailSelectActionPerformed
        accountNewEmailLbl.setEnabled(true);
        accountNewEmailField.setEnabled(true);
        accountPassLbl.setEnabled(true);
        accountPassField.setEnabled(true);
        accountChangeEmailBtn.setEnabled(true);
        accountOldPassLbl.setEnabled(false);
        accountOldPassField.setEnabled(false);
        accountNewPassLbl.setEnabled(false);
        accountNewPassField.setEnabled(false);
        accountNewPass2Lbl.setEnabled(false);
        accountNewPass2Field.setEnabled(false);
        accountChangePassBtn.setEnabled(false);
    }//GEN-LAST:event_accountChangeEmailSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffWindow(conn, user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountChangeEmailBtn;
    private javax.swing.JRadioButton accountChangeEmailSelect;
    private javax.swing.JButton accountChangePassBtn;
    private javax.swing.JRadioButton accountChangePassSelect;
    private javax.swing.ButtonGroup accountManagerSelector;
    private javax.swing.JTextField accountNewEmailField;
    private javax.swing.JLabel accountNewEmailLbl;
    private javax.swing.JPasswordField accountNewPass2Field;
    private javax.swing.JLabel accountNewPass2Lbl;
    private javax.swing.JPasswordField accountNewPassField;
    private javax.swing.JLabel accountNewPassLbl;
    private javax.swing.JPasswordField accountOldPassField;
    private javax.swing.JLabel accountOldPassLbl;
    private javax.swing.JTextField accountOrderCountField;
    private javax.swing.JLabel accountOrderCountLbl;
    private javax.swing.JPasswordField accountPassField;
    private javax.swing.JLabel accountPassLbl;
    private javax.swing.JLabel accountPerformanceLbl;
    private javax.swing.JScrollPane accountPerformanceSP;
    private javax.swing.JTable accountPerformanceTable;
    private javax.swing.JButton accountPrintReportBtn;
    private javax.swing.JPanel accountTab;
    private javax.swing.JButton orderCompleteBtn;
    private javax.swing.JList orderContentsList;
    private javax.swing.JScrollPane orderContentsScroll;
    private javax.swing.JButton orderPrintPendingBtn;
    private javax.swing.JButton orderProcessBtn;
    private javax.swing.JLabel ordersPendingLbl;
    private javax.swing.JScrollPane ordersScrollPane;
    private javax.swing.JLabel ordersSelectedLbl;
    private javax.swing.JPanel ordersTab;
    private javax.swing.JTable ordersTable;
    private javax.swing.JSeparator separator;
    private javax.swing.JTabbedPane staffTabs;
    // End of variables declaration//GEN-END:variables
}
